#include "capture_session.h"

#include "capture_lifecycle.h"
#include "frame_queue.h"
#include "progress_scheduler.h"
#include "size_policy.h"
#include "startup_coordinator.h"
#include "stop_watcher.h"
#include "string_utils.h"
#include "timeline.h"

#include <windows.h>
#include <windows.graphics.capture.interop.h>
#include <windows.graphics.directx.direct3d11.interop.h>
#include <d3d11.h>
#include <dxgi.h>
#include <mfapi.h>

// C++/WinRT projection headers (generated by cppwinrt.exe)
#include <winrt/Windows.Graphics.Capture.h>
#include <winrt/Windows.Graphics.DirectX.h>
#include <winrt/Windows.Graphics.DirectX.Direct3D11.h>
#include <winrt/Windows.Foundation.h>

#include <wrl/client.h>

#include <algorithm>
#include <chrono>
#include <condition_variable>
#include <cstdint>
#include <cstring>
#include <format>
#include <memory>
#include <mutex>
#include <thread>

namespace wgc {

namespace {

using namespace winrt::Windows::Graphics::Capture;
using namespace winrt::Windows::Graphics::DirectX;
using namespace winrt::Windows::Graphics::DirectX::Direct3D11;

using IDirect3DDxgiInterfaceAccess = ::Windows::Graphics::DirectX::Direct3D11::IDirect3DDxgiInterfaceAccess;

std::string HresultToString(HRESULT hr) {
    return std::format("0x{:08X}", static_cast<unsigned>(hr));
}

CaptureOutcome MakeFailWithEvidence(const std::string& errorCode,
                                    const std::string& reason,
                                    const std::string& hresult,
                                    const std::wstring& partialPath,
                                    int64_t framesCaptured,
                                    int64_t framesDropped,
                                    int64_t durationMs,
                                    int64_t bytesWritten,
                                    int width,
                                    int height) {
    CaptureOutcome outcome;
    outcome.result = CaptureResult::Failed;
    outcome.errorCode = errorCode;
    outcome.reason = reason;
    outcome.hresult = hresult;
    outcome.partialOutputPath = partialPath;
    outcome.framesCaptured = framesCaptured;
    outcome.framesDropped = framesDropped;
    outcome.durationMs = durationMs;
    outcome.bytesWritten = bytesWritten;
    outcome.width = width;
    outcome.height = height;
    return outcome;
}

CaptureOutcome MakeEarlyFail(const std::string& errorCode,
                             const std::string& reason,
                             const std::string& hresult = "") {
    return MakeFailWithEvidence(errorCode, reason, hresult, {}, 0, 0, 0, 0, 0, 0);
}

HRESULT CreateD3D11Device(Microsoft::WRL::ComPtr<ID3D11Device>& device,
                          Microsoft::WRL::ComPtr<ID3D11DeviceContext>& context) {
    UINT flags = D3D11_CREATE_DEVICE_BGRA_SUPPORT;
#if defined(_DEBUG)
    flags |= D3D11_CREATE_DEVICE_DEBUG;
#endif
    D3D_FEATURE_LEVEL featureLevels[] = { D3D_FEATURE_LEVEL_11_1, D3D_FEATURE_LEVEL_11_0 };
    return D3D11CreateDevice(nullptr, D3D_DRIVER_TYPE_HARDWARE, nullptr, flags,
                             featureLevels, static_cast<UINT>(std::size(featureLevels)),
                             D3D11_SDK_VERSION, &device, nullptr, &context);
}

struct MonitorEnumContext {
    Rect target;
    HMONITOR match = nullptr;
    int matchCount = 0;
};

BOOL CALLBACK MonitorEnumProc(HMONITOR hMonitor, HDC /*hdcMonitor*/,
                              LPRECT lprcMonitor, LPARAM dwData) {
    auto* ctx = reinterpret_cast<MonitorEnumContext*>(dwData);
    if (lprcMonitor->left == ctx->target.x && lprcMonitor->top == ctx->target.y &&
        lprcMonitor->right - lprcMonitor->left == ctx->target.width &&
        lprcMonitor->bottom - lprcMonitor->top == ctx->target.height) {
        ctx->match = hMonitor;
        ctx->matchCount++;
    }
    return TRUE;
}

int64_t SteadyMs(std::chrono::steady_clock::time_point tp) {
    return std::chrono::duration_cast<std::chrono::milliseconds>(tp.time_since_epoch()).count();
}

HRESULT CopyFrameToBgra(ID3D11Device* device,
                        const winrt::Windows::Graphics::Capture::Direct3D11CaptureFrame& frame,
                        int destWidth,
                        int destHeight,
                        std::vector<uint8_t>& outPixels) {
    if (!device || !frame) return E_INVALIDARG;
    if (destWidth <= 0 || destHeight <= 0) return E_INVALIDARG;

    auto surface = frame.Surface();
    if (!surface) return E_FAIL;

    auto dxgiAccess = surface.as<IDirect3DDxgiInterfaceAccess>();
    if (!dxgiAccess) return E_NOINTERFACE;

    Microsoft::WRL::ComPtr<ID3D11Texture2D> sourceTexture;
    HRESULT hr = dxgiAccess->GetInterface(__uuidof(ID3D11Texture2D),
                                          reinterpret_cast<void**>(sourceTexture.GetAddressOf()));
    if (FAILED(hr)) return hr;

    D3D11_TEXTURE2D_DESC desc = {};
    sourceTexture->GetDesc(&desc);
    const int sourceWidth = static_cast<int>(desc.Width);
    const int sourceHeight = static_cast<int>(desc.Height);
    if (destWidth > sourceWidth || destHeight > sourceHeight) {
        return E_UNEXPECTED;
    }

    D3D11_TEXTURE2D_DESC stagingDesc = {};
    stagingDesc.Width = static_cast<UINT>(destWidth);
    stagingDesc.Height = static_cast<UINT>(destHeight);
    stagingDesc.MipLevels = 1;
    stagingDesc.ArraySize = 1;
    stagingDesc.SampleDesc.Count = 1;
    stagingDesc.SampleDesc.Quality = 0;
    stagingDesc.Usage = D3D11_USAGE_STAGING;
    stagingDesc.BindFlags = 0;
    stagingDesc.CPUAccessFlags = D3D11_CPU_ACCESS_READ;
    stagingDesc.MiscFlags = 0;
    stagingDesc.Format = DXGI_FORMAT_B8G8R8A8_UNORM;

    Microsoft::WRL::ComPtr<ID3D11Texture2D> stagingTexture;
    hr = device->CreateTexture2D(&stagingDesc, nullptr, stagingTexture.GetAddressOf());
    if (FAILED(hr)) return hr;

    Microsoft::WRL::ComPtr<ID3D11DeviceContext> context;
    device->GetImmediateContext(context.GetAddressOf());

    D3D11_BOX srcBox = {};
    srcBox.left = 0;
    srcBox.top = 0;
    srcBox.front = 0;
    srcBox.right = static_cast<UINT>(destWidth);
    srcBox.bottom = static_cast<UINT>(destHeight);
    srcBox.back = 1;
    context->CopySubresourceRegion(stagingTexture.Get(), 0, 0, 0, 0,
                                   sourceTexture.Get(), 0, &srcBox);

    D3D11_MAPPED_SUBRESOURCE mapped = {};
    hr = context->Map(stagingTexture.Get(), 0, D3D11_MAP_READ, 0, &mapped);
    if (FAILED(hr)) return hr;

    const UINT rowPitch = mapped.RowPitch;
    const UINT destRowPitch = static_cast<UINT>(destWidth) * 4;
    outPixels.resize(static_cast<size_t>(destRowPitch) * destHeight);
    for (int row = 0; row < destHeight; ++row) {
        const uint8_t* src = static_cast<const uint8_t*>(mapped.pData) + static_cast<size_t>(row) * rowPitch;
        uint8_t* dst = outPixels.data() + static_cast<size_t>(row) * destRowPitch;
        std::memcpy(dst, src, destRowPitch);
    }

    context->Unmap(stagingTexture.Get(), 0);
    return S_OK;
}

int64_t GetFileSize(const std::wstring& path) {
    WIN32_FILE_ATTRIBUTE_DATA attrs = {};
    if (!::GetFileAttributesExW(path.c_str(), GetFileExInfoStandard, &attrs)) {
        return 0;
    }
    if (attrs.dwFileAttributes & FILE_ATTRIBUTE_DIRECTORY) {
        return 0;
    }
    LARGE_INTEGER size = {};
    size.LowPart = attrs.nFileSizeLow;
    size.HighPart = attrs.nFileSizeHigh;
    return size.QuadPart;
}

bool FileExists(const std::wstring& path) {
    return ::GetFileAttributesW(path.c_str()) != INVALID_FILE_ATTRIBUTES;
}

void RemoveEmptyPartial(const std::wstring& path) {
    if (path.empty()) return;
    if (!FileExists(path)) return;
    if (GetFileSize(path) == 0) {
        ::DeleteFileW(path.c_str());
    }
}

// Returns the partial path and its current size for failure evidence. Empty
// placeholder files are deleted and are not reported.
std::pair<std::wstring, int64_t> GetPartialEvidence(const std::wstring& partialPath) {
    if (partialPath.empty()) return { {}, 0 };
    RemoveEmptyPartial(partialPath);
    if (!FileExists(partialPath)) return { {}, 0 };
    return { partialPath, GetFileSize(partialPath) };
}

bool PublishPartialToFinal(const std::wstring& partial, const std::wstring& finalPath) {
    if (partial.empty() || finalPath.empty()) return false;
    return ::MoveFileExW(partial.c_str(), finalPath.c_str(), MOVEFILE_WRITE_THROUGH) != 0;
}

// Shared mutable state that may be accessed by frame callbacks after the main
// thread has begun teardown. Kept alive by shared_ptr until all in-flight
// callbacks have exited.
struct CapturePipelineState {
    explicit CapturePipelineState(size_t queueCapacity)
        : queue(queueCapacity) {}

    std::atomic<bool> stopRequested{false};
    std::atomic<bool> userStopped{false};
    std::atomic<bool> captureEnded{false};
    std::atomic<bool> sizeChanged{false};
    std::atomic<bool> captureFailed{false};
    std::atomic<HRESULT> copyFailedHr{S_OK};
    std::atomic<int64_t> framesDropped{0};
    // Written only by the encoder worker; read by the main/progress thread.
    std::atomic<int64_t> framesCaptured{0};

    FrameQueue queue;
    CaptureLifecycle lifecycle;
    StartupCoordinator coordinator;

    int sourceWidth = 0;
    int sourceHeight = 0;

    std::mutex loopMutex;
    std::condition_variable loopCv;

    // Called from any thread that decides capture should stop. Wakes the main
    // loop so it records the stop decision time promptly.
    void RequestStop(bool userStop) {
        stopRequested.store(true);
        if (userStop) {
            userStopped.store(true);
        }
        coordinator.RequestStop();
        loopCv.notify_all();
    }
};

void TeardownFramePool(const winrt::event_token& token,
                       GraphicsCaptureSession& session,
                       Direct3D11CaptureFramePool& framePool,
                       const std::shared_ptr<CapturePipelineState>& state,
                       bool* outCallbackDrainTimeout) {
    state->lifecycle.StopAccepting();
    // Revoke the subscription before closing so no new callbacks are scheduled
    // while we wait for in-flight callbacks to drain.
    try {
        framePool.FrameArrived(token);
    } catch (...) {
    }
    // Close the frame pool first so the event source stops firing; the
    // subscription token is released when the pool is destroyed.
    try {
        framePool.Close();
    } catch (...) {
    }
    try {
        session.Close();
    } catch (...) {
    }
    *outCallbackDrainTimeout = !state->lifecycle.WaitForCallbacks(std::chrono::milliseconds(2000));
}

bool TryJoinFor(std::thread& thread, std::chrono::milliseconds timeout) {
    if (!thread.joinable()) return true;
    HANDLE h = reinterpret_cast<HANDLE>(thread.native_handle());
    const DWORD ms = static_cast<DWORD>(std::min<int64_t>(timeout.count(), static_cast<int64_t>(INFINITE) - 1));
    if (::WaitForSingleObject(h, ms) == WAIT_OBJECT_0) {
        thread.join();
        return true;
    }
    return false;
}

// RAII wrapper that always joins on destruction. A stuck worker (e.g., hung
// Media Foundation init) cannot be safely cancelled inside the same process;
// the parent process watchdog is responsible for terminating the helper
// process if a worker never returns. Never detach.
struct ScopedThread {
    std::thread thread;

    ~ScopedThread() {
        if (thread.joinable()) {
            thread.join();
        }
    }

    bool TryJoinFor(std::chrono::milliseconds timeout) {
        return ::wgc::TryJoinFor(thread, timeout);
    }

    bool Joinable() const { return thread.joinable(); }
    void Join() { if (thread.joinable()) thread.join(); }
};

} // namespace

void WriteTerminalOutcome(EventWriter& writer, const CaptureOutcome& outcome) {
    switch (outcome.result) {
        case CaptureResult::Failed:
            writer.Fail(outcome.errorCode, outcome.reason, outcome.hresult,
                        outcome.partialOutputPath, outcome.framesCaptured,
                        outcome.bytesWritten);
            break;
        case CaptureResult::Stopped:
            writer.Stopped(outcome.framesCaptured, outcome.framesDropped,
                           outcome.durationMs, outcome.bytesWritten,
                           outcome.width, outcome.height);
            break;
        case CaptureResult::Success:
            writer.Ok(outcome.framesCaptured, outcome.framesDropped,
                      outcome.durationMs, outcome.bytesWritten,
                      outcome.width, outcome.height);
            break;
        default:
            writer.Fail("internal_error",
                        "unexpected capture outcome result value",
                        "", outcome.partialOutputPath,
                        outcome.framesCaptured, outcome.bytesWritten);
            break;
    }
}

CaptureOutcome NormalizeFailureEvidence(CaptureOutcome outcome,
                                        const std::wstring& canonicalPartialPath) {
    if (outcome.result != CaptureResult::Failed) {
        return outcome;
    }

    RemoveEmptyPartial(canonicalPartialPath);

    if (!canonicalPartialPath.empty() && FileExists(canonicalPartialPath)) {
        const int64_t size = GetFileSize(canonicalPartialPath);
        if (size > 0) {
            outcome.partialOutputPath = canonicalPartialPath;
            outcome.bytesWritten = size;
            return outcome;
        }
    }

    outcome.partialOutputPath.clear();
    outcome.bytesWritten = 0;
    return outcome;
}

CaptureSession::CaptureSession(const Options& options,
                               const std::wstring& outputPath,
                               const std::wstring& partialOutputPath,
                               BeginGate& gate,
                               EventWriter& writer)
    : options_(options),
      outputPath_(outputPath),
      partialOutputPath_(partialOutputPath),
      gate_(gate),
      writer_(writer),
      hooks_() {}

void CaptureSession::SetTestHooks(const CaptureSessionTestHooks& hooks) {
    hooks_ = hooks;
}

CaptureOutcome CaptureSession::Run() {
    HRESULT hr = CoInitializeEx(nullptr, COINIT_MULTITHREADED);
    const bool comInitialized = SUCCEEDED(hr);
    if (FAILED(hr) && hr != RPC_E_CHANGED_MODE) {
        return MakeEarlyFail("com_init_failed", "CoInitializeEx failed", HresultToString(hr));
    }
    struct ComGuard {
        bool needUninit;
        ~ComGuard() { if (needUninit) CoUninitialize(); }
    } comGuard{comInitialized};

    MonitorEnumContext monitorCtx;
    monitorCtx.target = options_.displayBounds;
    ::EnumDisplayMonitors(nullptr, nullptr, MonitorEnumProc, reinterpret_cast<LPARAM>(&monitorCtx));
    if (monitorCtx.match == nullptr) {
        return MakeEarlyFail("display_not_found", "No display exactly matches the requested bounds");
    }
    if (monitorCtx.matchCount > 1) {
        return MakeEarlyFail("display_ambiguous", "Multiple displays match the requested bounds");
    }

    Microsoft::WRL::ComPtr<ID3D11Device> d3dDevice;
    Microsoft::WRL::ComPtr<ID3D11DeviceContext> d3dContext;
    hr = CreateD3D11Device(d3dDevice, d3dContext);
    if (FAILED(hr)) {
        hr = D3D11CreateDevice(nullptr, D3D_DRIVER_TYPE_WARP, nullptr,
                               D3D11_CREATE_DEVICE_BGRA_SUPPORT,
                               nullptr, 0, D3D11_SDK_VERSION,
                               &d3dDevice, nullptr, &d3dContext);
        if (FAILED(hr)) {
            return MakeEarlyFail("d3d11_init_failed", "D3D11 device creation failed", HresultToString(hr));
        }
    }

    Microsoft::WRL::ComPtr<IDXGIDevice> dxgiDevice;
    hr = d3dDevice.As(&dxgiDevice);
    if (FAILED(hr)) {
        return MakeEarlyFail("dxgi_device_failed", "Failed to get DXGI device", HresultToString(hr));
    }

    IDirect3DDevice device{nullptr};
    hr = CreateDirect3D11DeviceFromDXGIDevice(dxgiDevice.Get(),
                                              reinterpret_cast<IInspectable**>(winrt::put_abi(device)));
    if (FAILED(hr)) {
        return MakeEarlyFail("direct3d_device_failed", "CreateDirect3D11DeviceFromDXGIDevice failed", HresultToString(hr));
    }

    GraphicsCaptureItem item{nullptr};
    {
        auto factory = winrt::get_activation_factory<GraphicsCaptureItem, IGraphicsCaptureItemInterop>();
        if (!factory) {
            return MakeEarlyFail("wgc_factory_failed", "Failed to get GraphicsCaptureItem factory");
        }
        winrt::Windows::Graphics::Capture::GraphicsCaptureItem abiItem{nullptr};
        hr = factory->CreateForMonitor(monitorCtx.match,
                                       winrt::guid_of<winrt::Windows::Graphics::Capture::GraphicsCaptureItem>(),
                                       reinterpret_cast<void**>(winrt::put_abi(abiItem)));
        if (FAILED(hr)) {
            return MakeEarlyFail("wgc_item_failed", "CreateForMonitor failed", HresultToString(hr));
        }
        item = abiItem;
    }

    const auto displaySize = item.Size();
    const int sourceWidth = displaySize.Width;
    const int sourceHeight = displaySize.Height;

    int captureWidth = 0;
    int captureHeight = 0;
    if (!ComputeCaptureDimensions(sourceWidth, sourceHeight, captureWidth, captureHeight)) {
        return MakeEarlyFail("display_size_unsupported",
                             std::format("Display size {}x{} is too small for capture", sourceWidth, sourceHeight));
    }

    constexpr int kFramePoolBufferCount = 2;
    const auto pixelFormat = DirectXPixelFormat::B8G8R8A8UIntNormalized;
    Direct3D11CaptureFramePool framePool = Direct3D11CaptureFramePool::CreateFreeThreaded(
        device, pixelFormat, kFramePoolBufferCount, item.Size());
    GraphicsCaptureSession session = framePool.CreateCaptureSession(item);

    // Leave the privacy border at its system-default value.

    auto state = std::make_shared<CapturePipelineState>(static_cast<size_t>(kFramePoolBufferCount - 1));
    state->sourceWidth = sourceWidth;
    state->sourceHeight = sourceHeight;

    if (hooks_.onStateCreated) {
        hooks_.onStateCreated(&state->lifecycle, state);
    }

    FrameTimeline timeline(options_.fps);
    VideoEncoder encoder;
    std::string encoderError;
    std::string encoderHresult;

    auto writeFrame = [&](const std::vector<uint8_t>& pixels,
                          int64_t mediaTimeHns,
                          int64_t durationHns) -> EncoderResult {
        EncoderResult result;
        if (hooks_.onWriteFrame) {
            result = hooks_.onWriteFrame(pixels, mediaTimeHns, durationHns);
        } else {
            result = encoder.WriteFrame(pixels, mediaTimeHns, durationHns);
        }
        if (result.status == EncoderStatus::Ok) {
            state->framesCaptured.fetch_add(1);
        }
        return result;
    };

    auto finalizeEncoder = [&]() -> EncoderResult {
        if (hooks_.onFinalize) {
            return hooks_.onFinalize();
        }
        return encoder.Finalize();
    };

    winrt::event_token frameToken = framePool.FrameArrived(
        [state](Direct3D11CaptureFramePool const& sender, winrt::Windows::Foundation::IInspectable const&) {
            CallbackGuard guard(state->lifecycle);
            if (!guard.Entered()) {
                return;
            }

            try {
                if (state->stopRequested.load() ||
                    state->coordinator.State() != StartupState::CaptureActive) {
                    return;
                }

                auto frame = sender.TryGetNextFrame();
                if (!frame) return;

                const auto contentSize = frame.ContentSize();
                if (IsContentSizeChanged(state->sourceWidth, state->sourceHeight,
                                         contentSize.Width, contentSize.Height)) {
                    state->sizeChanged.store(true);
                    state->RequestStop(false);
                    return;
                }

                QueuedFrame qf;
                qf.frame = frame;
                qf.systemRelativeTimeHns = frame.SystemRelativeTime().count();
                qf.contentWidth = contentSize.Width;
                qf.contentHeight = contentSize.Height;

                if (!state->queue.Push(qf)) {
                    // Queue rejected the frame (shutdown). Close it here.
                    if (qf.frame) {
                        try {
                            qf.frame.Close();
                        } catch (...) {
                        }
                    }
                }
            } catch (...) {
                state->framesDropped.fetch_add(1);
            }
        });

    ScopedThread encoderThread{std::thread([&, state]() {
        // Wait for begin authorization before initializing anything that would
        // write screen frames. This guarantees that a COM/encoder failure is
        // reported while the coordinator is in EncoderInitializing.
        if (!state->coordinator.WaitForBeginAuthorization(std::chrono::milliseconds(options_.beginTimeoutMs + 1000))) {
            return;
        }

        HRESULT comHr = CoInitializeEx(nullptr, COINIT_MULTITHREADED);
        const bool threadComInitialized = SUCCEEDED(comHr);
        if (FAILED(comHr) && comHr != RPC_E_CHANGED_MODE) {
            state->coordinator.SignalEncoderFailed("COM initialization failed for encoder thread",
                                                   HresultToString(comHr));
            return;
        }
        struct ThreadComGuard {
            bool need;
            ~ThreadComGuard() { if (need) CoUninitialize(); }
        } threadComGuard{threadComInitialized};

        EncoderResult initResult;
        if (hooks_.onEncoderInitialize) {
            initResult = hooks_.onEncoderInitialize(captureWidth, captureHeight, options_.fps,
                                                     partialOutputPath_);
        } else {
            initResult = encoder.Initialize(captureWidth, captureHeight, options_.fps, partialOutputPath_);
        }
        if (initResult.status != EncoderStatus::Ok) {
            state->coordinator.SignalEncoderFailed(initResult.error, initResult.hresult);
            return;
        }

        state->coordinator.SignalEncoderReady();

        if (!state->coordinator.WaitForCaptureActive(std::chrono::milliseconds(options_.beginTimeoutMs + 1000))) {
            return;
        }

        const int64_t beginTimeMs = state->coordinator.BeginTimeMs();
        const int64_t endTimeMs = beginTimeMs + options_.durationMs;

        while (!state->captureEnded.load()) {
            QueuedFrame qf;
            bool gotFrame = state->queue.Pop(qf, std::chrono::milliseconds(50));

            const auto nowMs = SteadyMs(std::chrono::steady_clock::now());
            if (nowMs >= endTimeMs || state->stopRequested.load() ||
                state->coordinator.State() == StartupState::Stopping ||
                state->coordinator.State() == StartupState::Stopped) {
                if (qf.frame) {
                    try { qf.frame.Close(); } catch (...) {}
                }
                break;
            }

            if (gotFrame && (qf.frame || hooks_.onCopyFrame)) {
                int64_t mediaTimeHns = 0;
                int64_t durationHns = 0;
                if (!timeline.SubmitFrame(qf.systemRelativeTimeHns, &mediaTimeHns, &durationHns)) {
                    state->framesDropped.fetch_add(1);
                    if (qf.frame) {
                        try { qf.frame.Close(); } catch (...) {}
                    }
                    continue;
                }

                std::vector<uint8_t> pixels;
                HRESULT copyHr = S_OK;
                if (hooks_.onCopyFrame) {
                    if (!hooks_.onCopyFrame(qf, captureWidth, captureHeight, pixels)) {
                        copyHr = E_FAIL;
                    }
                } else {
                    copyHr = CopyFrameToBgra(d3dDevice.Get(), qf.frame,
                                             captureWidth, captureHeight, pixels);
                }
                if (qf.frame) {
                    try { qf.frame.Close(); } catch (...) {}
                }

                if (FAILED(copyHr)) {
                    state->copyFailedHr.store(copyHr);
                    state->captureFailed.store(true);
                    state->RequestStop(false);
                    break;
                }

                EncoderResult writeResult = writeFrame(pixels, mediaTimeHns, durationHns);
                if (writeResult.status != EncoderStatus::Ok) {
                    encoderError = writeResult.error;
                    encoderHresult = writeResult.hresult;
                    state->captureFailed.store(true);
                    state->RequestStop(false);
                    break;
                }
            }
        }

        state->queue.Shutdown();
        EncoderResult finalizeResult = finalizeEncoder();
        if (finalizeResult.status != EncoderStatus::Ok && encoderError.empty()) {
            encoderError = finalizeResult.error;
            encoderHresult = finalizeResult.hresult;
            state->captureFailed.store(true);
        }
    })};

    // Single begin time used for both coordinator and duration measurement.
    std::chrono::steady_clock::time_point beginTime;

    // Production source for "bytes written" evidence: the partial file's real
    // size on disk. Tests can override this to avoid depending on a real
    // encoder, but the override must still represent file-size semantics.
    auto GetOutputBytes = [&]() -> int64_t {
        if (hooks_.onGetOutputBytes) {
            return hooks_.onGetOutputBytes();
        }
        if (partialOutputPath_.empty()) {
            return 0;
        }
        return GetFileSize(partialOutputPath_);
    };

    // RAII guard that guarantees coordinator.MarkCaptureEnded() is invoked
    // exactly once on every return path after state has been created. This is
    // distinct from the IPC terminal event, which is owned by main.cpp.
    struct CaptureEndedGuard {
        StartupCoordinator& coordinator;
        std::function<void()> onMarkCaptureEnded;
        ~CaptureEndedGuard() {
            if (onMarkCaptureEnded) onMarkCaptureEnded();
            coordinator.MarkCaptureEnded();
        }
    };
    CaptureEndedGuard captureEndedGuard{state->coordinator, hooks_.onMarkCaptureEnded};

    auto FailAndTeardown = [&](const std::string& errorCode,
                               const std::string& reason,
                               const std::string& hresult = "") -> CaptureOutcome {
        const auto stopDecisionTime = std::chrono::steady_clock::now();
        const int64_t durationMs = (beginTime.time_since_epoch().count() > 0)
            ? std::chrono::duration_cast<std::chrono::milliseconds>(stopDecisionTime - beginTime).count()
            : 0;
        const int64_t framesCaptured = state->framesCaptured.load();
        const int64_t framesDropped = state->framesDropped.load() + state->queue.Dropped();

        state->RequestStop(false);
        state->captureEnded.store(true);
        state->queue.Shutdown();
        encoderThread.Join();

        bool callbackDrainTimeout = false;
        TeardownFramePool(frameToken, session, framePool, state, &callbackDrainTimeout);

        auto [partialPath, bytesWritten] = GetPartialEvidence(partialOutputPath_);
        if (callbackDrainTimeout) {
            return MakeFailWithEvidence("callback_drain_timeout",
                                        "Timed out waiting for frame callbacks to exit",
                                        "", partialPath,
                                        framesCaptured, framesDropped, durationMs, bytesWritten,
                                        captureWidth, captureHeight);
        }
        return MakeFailWithEvidence(errorCode, reason, hresult, partialPath,
                                    framesCaptured, framesDropped, durationMs, bytesWritten,
                                    captureWidth, captureHeight);
    };

    // Wait for begin authorization before touching capture session.
    BeginGateResult gateResult = gate_.WaitAndRun([&]() {
        state->coordinator.AuthorizeBegin();
    });

    if (gateResult != BeginGateResult::Started) {
        // Ensure the encoder worker exits cleanly.
        state->coordinator.AuthorizeBegin();
        state->coordinator.SignalEncoderFailed("begin_not_granted", "");
        state->captureEnded.store(true);
        state->queue.Shutdown();
        encoderThread.Join();

        bool callbackDrainTimeout = false;
        TeardownFramePool(frameToken, session, framePool, state, &callbackDrainTimeout);

        // Begin failures only produce an empty placeholder; do not report it.
        RemoveEmptyPartial(partialOutputPath_);

        switch (gateResult) {
            case BeginGateResult::Timeout:
                return MakeEarlyFail("timeout", "Begin signal not received before timeout");
            case BeginGateResult::Cancelled:
                return MakeEarlyFail("cancelled", "Capture was cancelled before begin");
            case BeginGateResult::InvalidToken:
                return MakeEarlyFail("invalid_token", "Begin signal token mismatch");
            case BeginGateResult::CancelledBeforeBegin:
                return MakeEarlyFail("cancelled_before_begin", "Stop signal existed before begin authorization");
            case BeginGateResult::InternalError:
                return MakeEarlyFail("start_callback_failed", "StartCapture callback raised an exception");
            default:
                return MakeEarlyFail("begin_failed", "Failed to obtain begin authorization");
        }
    }

    // Wait for the encoder to finish initializing before starting capture.
    EncoderInitResult initResult = state->coordinator.WaitForEncoderInit(
        std::chrono::milliseconds(options_.beginTimeoutMs + 1000));

    if (initResult.status == EncoderInitStatus::TimedOut) {
        // A hung Media Foundation initialization cannot be cancelled from inside
        // the helper. Join the worker deterministically; if it never returns,
        // the parent process watchdog is responsible for terminating the helper.
        state->RequestStop(false);
        state->captureEnded.store(true);
        state->queue.Shutdown();
        encoderThread.Join();

        bool callbackDrainTimeout = false;
        TeardownFramePool(frameToken, session, framePool, state, &callbackDrainTimeout);

        auto [partialPath, bytesWritten] = GetPartialEvidence(partialOutputPath_);
        return MakeFailWithEvidence("encoder_init_timeout",
                                    "Encoder did not become ready in time",
                                    "", partialPath, 0, 0, 0, bytesWritten,
                                    captureWidth, captureHeight);
    }
    if (initResult.status == EncoderInitStatus::Failed) {
        return FailAndTeardown("encoder_init_failed", initResult.error, initResult.hresult);
    }
    if (initResult.status == EncoderInitStatus::Stopped) {
        return FailAndTeardown("stopped_before_capture", "Capture was stopped before capture became active");
    }

    // Single clock: record begin time, start capture, then publish active state.
    beginTime = std::chrono::steady_clock::now();
    const int64_t beginTimeMs = SteadyMs(beginTime);

    try {
        if (hooks_.onStartCapture) {
            hooks_.onStartCapture();
        } else {
            session.StartCapture();
        }
    } catch (...) {
        return FailAndTeardown("start_capture_failed", "StartCapture raised an exception");
    }

    const auto deadline = beginTime + std::chrono::milliseconds(options_.durationMs);

    writer_.Started(WideToUtf8(options_.recordingId), outputPath_, options_.fps,
                    captureWidth, captureHeight);
    if (hooks_.onStarted) {
        hooks_.onStarted();
    }
    state->coordinator.SignalCaptureStarted(beginTimeMs);

    if (hooks_.onCaptureActive) {
        hooks_.onCaptureActive(state->queue);
    }

    StopSignalWatcher stopWatcher(options_.stopSignalPath, state->stopRequested, state->userStopped,
                                  [&]() { state->loopCv.notify_all(); });
    stopWatcher.Start();

    ProgressScheduler scheduler([&](const ProgressSnapshot& snapshot) {
        writer_.Progress(snapshot.framesCaptured,
                         snapshot.framesDropped,
                         snapshot.elapsedMs,
                         snapshot.bytesWritten);
    }, std::chrono::milliseconds(1000));
    scheduler.Start(beginTimeMs);

    {
        std::unique_lock<std::mutex> lock(state->loopMutex);
        while (std::chrono::steady_clock::now() < deadline && !state->stopRequested.load()) {
            const auto now = std::chrono::steady_clock::now();
            ProgressSnapshot snapshot;
            snapshot.framesCaptured = state->framesCaptured.load();
            snapshot.framesDropped = state->framesDropped.load() + state->queue.Dropped();
            snapshot.elapsedMs = SteadyMs(now) - beginTimeMs;
            snapshot.bytesWritten = GetOutputBytes();
            if (hooks_.onProgressSnapshot) {
                hooks_.onProgressSnapshot(snapshot);
            }
            scheduler.MaybeEmit(snapshot);

            const auto waitUntil = std::min(deadline, scheduler.NextProgressTime());
            state->loopCv.wait_until(lock, waitUntil, [&] {
                return state->stopRequested.load() || state->captureFailed.load() ||
                       state->sizeChanged.load() || std::chrono::steady_clock::now() >= waitUntil;
            });
        }
    }

    const auto stopDecisionTime = std::chrono::steady_clock::now();
    const int64_t durationMs = std::chrono::duration_cast<std::chrono::milliseconds>(stopDecisionTime - beginTime).count();

    stopWatcher.Stop();
    scheduler.Stop();
    state->RequestStop(false);
    state->lifecycle.StopAccepting();

    // Teardown: stop producing frames, wait for callbacks, then stop consuming.
    bool callbackDrainTimeout = false;
    TeardownFramePool(frameToken, session, framePool, state, &callbackDrainTimeout);

    state->captureEnded.store(true);
    state->queue.Shutdown();
    encoderThread.Join();

    const int64_t framesCaptured = state->framesCaptured.load();
    const int64_t framesDropped = state->framesDropped.load() + state->queue.Dropped();

    CaptureOutcome outcome;

    if (callbackDrainTimeout) {
        auto [partialPath, bytesWritten] = GetPartialEvidence(partialOutputPath_);
        outcome = MakeFailWithEvidence("callback_drain_timeout",
                                       "Timed out waiting for frame callbacks to exit",
                                       "", partialPath,
                                       framesCaptured, framesDropped, durationMs, bytesWritten,
                                       captureWidth, captureHeight);
    } else if (state->sizeChanged.load()) {
        auto [partialPath, bytesWritten] = GetPartialEvidence(partialOutputPath_);
        outcome = MakeFailWithEvidence("size_changed", "Frame content size changed during capture", "",
                                       partialPath, framesCaptured, framesDropped, durationMs,
                                       bytesWritten, captureWidth, captureHeight);
    } else if (state->captureFailed.load()) {
        auto [partialPath, bytesWritten] = GetPartialEvidence(partialOutputPath_);
        if (state->copyFailedHr.load() != S_OK) {
            outcome = MakeFailWithEvidence("d3d_copy_failed", "Failed to copy frame from GPU",
                                           HresultToString(state->copyFailedHr.load()), partialPath,
                                           framesCaptured, framesDropped, durationMs, bytesWritten,
                                           captureWidth, captureHeight);
        } else if (!encoderError.empty()) {
            outcome = MakeFailWithEvidence("encoding_error", encoderError, encoderHresult, partialPath,
                                           framesCaptured, framesDropped, durationMs, bytesWritten,
                                           captureWidth, captureHeight);
        } else {
            outcome = MakeFailWithEvidence("capture_failed", "Capture failed during encoding", "", partialPath,
                                           framesCaptured, framesDropped, durationMs, bytesWritten,
                                           captureWidth, captureHeight);
        }
    } else if (framesCaptured == 0) {
        // No frames means the partial (if any) is not useful evidence.
        if (!partialOutputPath_.empty() && FileExists(partialOutputPath_)) {
            ::DeleteFileW(partialOutputPath_.c_str());
        }
        outcome = MakeFailWithEvidence("zero_frames", "No frames were captured", "", {},
                                       0, framesDropped, durationMs, 0,
                                       captureWidth, captureHeight);
    } else {
        // Common publish path for both Success and explicit user Stopped.
        if (!PublishPartialToFinal(partialOutputPath_, outputPath_)) {
            auto [partialPath, bytesWritten] = GetPartialEvidence(partialOutputPath_);
            const DWORD err = ::GetLastError();
            outcome = MakeFailWithEvidence("publish_failed",
                                           std::format("MoveFileEx failed: {}", err), "",
                                           partialPath, framesCaptured, framesDropped, durationMs,
                                           bytesWritten, captureWidth, captureHeight);
        } else {
            const int64_t finalSize = GetFileSize(outputPath_);
            if (finalSize == 0) {
                // Do not leave an invalid empty file at the target path.
                ::DeleteFileW(outputPath_.c_str());
                outcome = MakeFailWithEvidence("invalid_output",
                                               "Final output file is empty after publish", "", {},
                                               framesCaptured, framesDropped, durationMs, 0,
                                               captureWidth, captureHeight);
            } else {
                if (state->userStopped.load()) {
                    outcome.result = CaptureResult::Stopped;
                } else {
                    outcome.result = CaptureResult::Success;
                }
                outcome.framesCaptured = framesCaptured;
                outcome.framesDropped = framesDropped;
                outcome.durationMs = durationMs;
                outcome.bytesWritten = finalSize;
                outcome.width = captureWidth;
                outcome.height = captureHeight;
            }
        }
    }

    // CaptureSession returns a complete outcome; the terminal IPC event is
    // emitted exactly once by main.cpp (the single terminal owner).
    return outcome;
}

} // namespace wgc
