#include "capture_session.h"

#include "capture_lifecycle.h"
#include "display_geometry.h"
#include "frame_queue.h"
#include "progress_scheduler.h"
#include "size_policy.h"
#include "startup_coordinator.h"
#include "stop_watcher.h"
#include "string_utils.h"
#include "timeline.h"

#include <windows.h>
#include <windows.graphics.capture.interop.h>
#include <windows.graphics.directx.direct3d11.interop.h>
#include <d3d11.h>
#include <dxgi.h>
#include <mfapi.h>

// C++/WinRT projection headers (generated by cppwinrt.exe)
#include <winrt/Windows.Graphics.Capture.h>
#include <winrt/Windows.Graphics.DirectX.h>
#include <winrt/Windows.Graphics.DirectX.Direct3D11.h>
#include <winrt/Windows.Foundation.h>

#include <wrl/client.h>

#include <algorithm>
#include <chrono>
#include <condition_variable>
#include <cstdint>
#include <cstring>
#include <format>
#include <limits>
#include <memory>
#include <mutex>
#include <optional>
#include <thread>

namespace wgc {

namespace {

using namespace winrt::Windows::Graphics::Capture;
using namespace winrt::Windows::Graphics::DirectX;
using namespace winrt::Windows::Graphics::DirectX::Direct3D11;

using IDirect3DDxgiInterfaceAccess = ::Windows::Graphics::DirectX::Direct3D11::IDirect3DDxgiInterfaceAccess;

std::string HresultToString(HRESULT hr) {
    return std::format("0x{:08X}", static_cast<unsigned>(hr));
}

CaptureOutcome MakeFailWithEvidence(const std::string& errorCode,
                                    const std::string& reason,
                                    const std::string& hresult,
                                    const std::wstring& partialPath,
                                    int64_t framesCaptured,
                                    int64_t framesDropped,
                                    int64_t durationMs,
                                    int64_t bytesWritten,
                                    int width,
                                    int height) {
    CaptureOutcome outcome;
    outcome.result = CaptureResult::Failed;
    outcome.errorCode = errorCode;
    outcome.reason = reason;
    outcome.hresult = hresult;
    outcome.partialOutputPath = partialPath;
    outcome.framesCaptured = framesCaptured;
    outcome.framesDropped = framesDropped;
    outcome.durationMs = durationMs;
    outcome.bytesWritten = bytesWritten;
    outcome.width = width;
    outcome.height = height;
    return outcome;
}

CaptureOutcome MakeEarlyFail(const std::string& errorCode,
                             const std::string& reason,
                             const std::string& hresult = "") {
    return MakeFailWithEvidence(errorCode, reason, hresult, {}, 0, 0, 0, 0, 0, 0);
}

HRESULT CreateD3D11Device(Microsoft::WRL::ComPtr<ID3D11Device>& device,
                          Microsoft::WRL::ComPtr<ID3D11DeviceContext>& context) {
    UINT flags = D3D11_CREATE_DEVICE_BGRA_SUPPORT;
#if defined(_DEBUG)
    flags |= D3D11_CREATE_DEVICE_DEBUG;
#endif
    D3D_FEATURE_LEVEL featureLevels[] = { D3D_FEATURE_LEVEL_11_1, D3D_FEATURE_LEVEL_11_0 };
    return D3D11CreateDevice(nullptr, D3D_DRIVER_TYPE_HARDWARE, nullptr, flags,
                             featureLevels, static_cast<UINT>(std::size(featureLevels)),
                             D3D11_SDK_VERSION, &device, nullptr, &context);
}

struct MonitorEnumContext {
    Rect target;
    HMONITOR match = nullptr;
    int matchCount = 0;
};

BOOL CALLBACK MonitorEnumProc(HMONITOR hMonitor, HDC /*hdcMonitor*/,
                              LPRECT lprcMonitor, LPARAM dwData) {
    auto* ctx = reinterpret_cast<MonitorEnumContext*>(dwData);
    if (RectExactlyMatchesMonitor(ctx->target, *lprcMonitor)) {
        ctx->match = hMonitor;
        ctx->matchCount++;
    }
    return TRUE;
}

bool IsConfiguredDisplayAvailable(const Rect& target, HMONITOR expectedMonitor = nullptr) {
    MonitorEnumContext context;
    context.target = target;
    if (!::EnumDisplayMonitors(nullptr, nullptr, MonitorEnumProc,
                               reinterpret_cast<LPARAM>(&context))) {
        return false;
    }
    return context.matchCount == 1 &&
           (expectedMonitor == nullptr || context.match == expectedMonitor);
}

int64_t SteadyMs(std::chrono::steady_clock::time_point tp) {
    return std::chrono::duration_cast<std::chrono::milliseconds>(tp.time_since_epoch()).count();
}

HRESULT CopyFrameToBgra(ID3D11Device* device,
                        const winrt::Windows::Graphics::Capture::Direct3D11CaptureFrame& frame,
                        int destWidth,
                        int destHeight,
                        int sourceOffsetX,
                        int sourceOffsetY,
                        std::vector<uint8_t>& outPixels) {
    if (!device || !frame) return E_INVALIDARG;
    if (destWidth <= 0 || destHeight <= 0) return E_INVALIDARG;
    if (sourceOffsetX < 0 || sourceOffsetY < 0) return E_INVALIDARG;

    auto surface = frame.Surface();
    if (!surface) return E_FAIL;

    auto dxgiAccess = surface.as<IDirect3DDxgiInterfaceAccess>();
    if (!dxgiAccess) return E_NOINTERFACE;

    Microsoft::WRL::ComPtr<ID3D11Texture2D> sourceTexture;
    HRESULT hr = dxgiAccess->GetInterface(__uuidof(ID3D11Texture2D),
                                          reinterpret_cast<void**>(sourceTexture.GetAddressOf()));
    if (FAILED(hr)) return hr;
    return CopyTextureRegionToBgra(device,
                                   sourceTexture.Get(),
                                   sourceOffsetX,
                                   sourceOffsetY,
                                   destWidth,
                                   destHeight,
                                   outPixels);
}

int64_t GetFileSize(const std::wstring& path) {
    WIN32_FILE_ATTRIBUTE_DATA attrs = {};
    if (!::GetFileAttributesExW(path.c_str(), GetFileExInfoStandard, &attrs)) {
        return 0;
    }
    if (attrs.dwFileAttributes & FILE_ATTRIBUTE_DIRECTORY) {
        return 0;
    }
    LARGE_INTEGER size = {};
    size.LowPart = attrs.nFileSizeLow;
    size.HighPart = attrs.nFileSizeHigh;
    return size.QuadPart;
}

bool FileExists(const std::wstring& path) {
    return ::GetFileAttributesW(path.c_str()) != INVALID_FILE_ATTRIBUTES;
}

void RemoveEmptyPartial(const std::wstring& path) {
    if (path.empty()) return;
    if (!FileExists(path)) return;
    if (GetFileSize(path) == 0) {
        ::DeleteFileW(path.c_str());
    }
}

// Returns the partial path and its current size for failure evidence. Empty
// placeholder files are deleted and are not reported.
std::pair<std::wstring, int64_t> GetPartialEvidence(const std::wstring& partialPath) {
    if (partialPath.empty()) return { {}, 0 };
    RemoveEmptyPartial(partialPath);
    if (!FileExists(partialPath)) return { {}, 0 };
    return { partialPath, GetFileSize(partialPath) };
}

bool PublishPartialToFinal(const std::wstring& partial, const std::wstring& finalPath) {
    if (partial.empty() || finalPath.empty()) return false;
    return ::MoveFileExW(partial.c_str(), finalPath.c_str(), MOVEFILE_WRITE_THROUGH) != 0;
}

// Shared mutable state that may be accessed by frame callbacks after the main
// thread has begun teardown. Kept alive by shared_ptr until all in-flight
// callbacks have exited.
struct CapturePipelineState {
    explicit CapturePipelineState(size_t queueCapacity)
        : queue(queueCapacity) {}

    std::atomic<bool> stopRequested{false};
    std::atomic<bool> userStopped{false};
    std::atomic<bool> captureEnded{false};
    std::atomic<bool> sizeChanged{false};
    std::atomic<bool> targetClosed{false};
    std::atomic<bool> targetMinimized{false};
    std::atomic<bool> displayUnavailable{false};
    std::atomic<bool> captureFailed{false};
    enum class RuntimeSignal : int {
        None = 0,
        WindowClosed,
        WindowMinimized,
        DisplayUnavailable,
        SizeChanged,
        CaptureFailed
    };
    std::atomic<RuntimeSignal> runtimeSignal{RuntimeSignal::None};
    std::atomic<HRESULT> copyFailedHr{S_OK};
    std::atomic<int64_t> framesDropped{0};
    // Written only by the encoder worker; read by the main/progress thread.
    std::atomic<int64_t> framesCaptured{0};

    FrameQueue queue;
    CaptureLifecycle lifecycle;
    StartupCoordinator coordinator;

    int sourceWidth = 0;
    int sourceHeight = 0;
    EncoderMode encoderMode = EncoderMode::Software;
    EncoderSelectionReason encoderSelectionReason = EncoderSelectionReason::SoftwareDefault;
    bool encoderSelectionKnown = false;

    std::mutex loopMutex;
    std::condition_variable loopCv;

    // Called from any thread that decides capture should stop. Wakes the main
    // loop so it records the stop decision time promptly.
    void RequestStop(bool userStop) {
        stopRequested.store(true);
        if (userStop) {
            userStopped.store(true);
        }
        coordinator.RequestStop();
        loopCv.notify_all();
    }

    bool SignalRuntime(RuntimeSignal signal) {
        // A single first-writer decision keeps close/minimize/resize and
        // encoder failures deterministic when callbacks race with teardown.
        if (stopRequested.load()) {
            return false;
        }
        RuntimeSignal expected = RuntimeSignal::None;
        if (!runtimeSignal.compare_exchange_strong(expected, signal)) {
            return false;
        }
        if (signal == RuntimeSignal::WindowClosed) {
            targetClosed.store(true);
        } else if (signal == RuntimeSignal::WindowMinimized) {
            targetMinimized.store(true);
        } else if (signal == RuntimeSignal::DisplayUnavailable) {
            displayUnavailable.store(true);
        } else if (signal == RuntimeSignal::SizeChanged) {
            sizeChanged.store(true);
        } else if (signal == RuntimeSignal::CaptureFailed) {
            captureFailed.store(true);
        }
        RequestStop(false);
        return true;
    }

    void SignalWindowClosed() { SignalRuntime(RuntimeSignal::WindowClosed); }
    void SignalWindowMinimized() { SignalRuntime(RuntimeSignal::WindowMinimized); }
    void SignalDisplayUnavailable() { SignalRuntime(RuntimeSignal::DisplayUnavailable); }
    void SignalSizeChanged() { SignalRuntime(RuntimeSignal::SizeChanged); }
    void SignalCaptureFailure() {
        captureFailed.store(true);
        if (runtimeSignal.load() == RuntimeSignal::None) {
            SignalRuntime(RuntimeSignal::CaptureFailed);
        } else {
            RequestStop(false);
        }
    }
};

// Polls only the canonical HWND for active window captures. The condition
// variable bounds the interval and lets teardown stop/join the monitor without
// a busy loop or a detached thread.
class WindowLifecycleMonitor {
public:
    using Query = std::function<CaptureSessionTestWindowState(std::uint64_t)>;

    WindowLifecycleMonitor(std::uint64_t hwnd,
                           Query query,
                           std::function<void()> onClosed,
                           std::function<void()> onMinimized)
        : hwnd_(hwnd),
          query_(std::move(query)),
          onClosed_(std::move(onClosed)),
          onMinimized_(std::move(onMinimized)) {}

    ~WindowLifecycleMonitor() { Stop(); }

    void Start() {
        if (thread_.joinable()) return;
        thread_ = std::thread([this]() { Run(); });
    }

    void Stop() {
        {
            std::lock_guard<std::mutex> lock(mutex_);
            stop_ = true;
        }
        cv_.notify_all();
        if (thread_.joinable()) {
            thread_.join();
        }
    }

private:
    void Run() {
        constexpr auto kPollInterval = std::chrono::milliseconds(50);
        for (;;) {
            CaptureSessionTestWindowState state;
            try {
                state = query_(hwnd_);
            } catch (...) {
                state.isWindow = false;
            }

            if (!state.isWindow) {
                onClosed_();
                return;
            }
            if (state.isIconic) {
                onMinimized_();
                return;
            }

            std::unique_lock<std::mutex> lock(mutex_);
            if (cv_.wait_for(lock, kPollInterval, [this]() { return stop_; })) {
                return;
            }
        }
    }

    std::uint64_t hwnd_;
    Query query_;
    std::function<void()> onClosed_;
    std::function<void()> onMinimized_;
    std::mutex mutex_;
    std::condition_variable cv_;
    bool stop_ = false;
    std::thread thread_;
};

// Polls only the exact, approved display bounds for display and region
// captures. No display identity or device path is exposed. A failed topology
// query is deliberately fail-closed so a transient/unsupported query cannot
// silently continue capturing a lost target.
class DisplayLifecycleMonitor {
public:
    using Query = std::function<bool(const Rect&)>;

    DisplayLifecycleMonitor(Rect target,
                            Query query,
                            std::function<void()> onUnavailable)
        : target_(target),
          query_(std::move(query)),
          onUnavailable_(std::move(onUnavailable)) {}

    ~DisplayLifecycleMonitor() { Stop(); }

    void Start() {
        if (thread_.joinable()) return;
        thread_ = std::thread([this]() { Run(); });
    }

    void Stop() {
        {
            std::lock_guard<std::mutex> lock(mutex_);
            stop_ = true;
        }
        cv_.notify_all();
        if (thread_.joinable()) {
            thread_.join();
        }
    }

private:
    void Run() {
        constexpr auto kPollInterval = std::chrono::milliseconds(50);
        for (;;) {
            bool available = false;
            try {
                available = query_(target_);
            } catch (...) {
                available = false;
            }

            if (!available) {
                onUnavailable_();
                return;
            }

            std::unique_lock<std::mutex> lock(mutex_);
            if (cv_.wait_for(lock, kPollInterval, [this]() { return stop_; })) {
                return;
            }
        }
    }

    Rect target_;
    Query query_;
    std::function<void()> onUnavailable_;
    std::mutex mutex_;
    std::condition_variable cv_;
    bool stop_ = false;
    std::thread thread_;
};

void TeardownFramePool(bool hasCaptureResources,
                       GraphicsCaptureItem& item,
                       bool hasItemClosedSubscription,
                       const winrt::event_token& itemClosedToken,
                       const winrt::event_token& token,
                       GraphicsCaptureSession& session,
                       Direct3D11CaptureFramePool& framePool,
                       const std::shared_ptr<CapturePipelineState>& state,
                       bool* outCallbackDrainTimeout) {
    state->lifecycle.StopAccepting();
    // Revoke the subscription before closing so no new callbacks are scheduled
    // while we wait for in-flight callbacks to drain.
    if (hasCaptureResources) {
        if (hasItemClosedSubscription) {
            try {
                item.Closed(itemClosedToken);
            } catch (...) {
            }
        }
        try {
            framePool.FrameArrived(token);
        } catch (...) {
        }
        // Close the frame pool first so the event source stops firing; the
        // subscription token is released when the pool is destroyed.
        try {
            framePool.Close();
        } catch (...) {
        }
        try {
            session.Close();
        } catch (...) {
        }
    }
    *outCallbackDrainTimeout = !state->lifecycle.WaitForCallbacks(std::chrono::milliseconds(2000));
}

bool TryJoinFor(std::thread& thread, std::chrono::milliseconds timeout) {
    if (!thread.joinable()) return true;
    HANDLE h = reinterpret_cast<HANDLE>(thread.native_handle());
    const DWORD ms = static_cast<DWORD>(std::min<int64_t>(timeout.count(), static_cast<int64_t>(INFINITE) - 1));
    if (::WaitForSingleObject(h, ms) == WAIT_OBJECT_0) {
        thread.join();
        return true;
    }
    return false;
}

// RAII wrapper that always joins on destruction. A stuck worker (e.g., hung
// Media Foundation init) cannot be safely cancelled inside the same process;
// the parent process watchdog is responsible for terminating the helper
// process if a worker never returns. Never detach.
struct ScopedThread {
    std::thread thread;

    ~ScopedThread() {
        if (thread.joinable()) {
            thread.join();
        }
    }

    bool TryJoinFor(std::chrono::milliseconds timeout) {
        return ::wgc::TryJoinFor(thread, timeout);
    }

    bool Joinable() const { return thread.joinable(); }
    void Join() { if (thread.joinable()) thread.join(); }
};

} // namespace

HRESULT CopyTextureRegionToBgra(ID3D11Device* device,
                                ID3D11Texture2D* sourceTexture,
                                int sourceOffsetX,
                                int sourceOffsetY,
                                int destWidth,
                                int destHeight,
                                std::vector<uint8_t>& outPixels) {
    outPixels.clear();
    if (!device || !sourceTexture ||
        sourceOffsetX < 0 || sourceOffsetY < 0 ||
        destWidth <= 0 || destHeight <= 0 ||
        static_cast<uint64_t>(destWidth) > std::numeric_limits<UINT>::max() ||
        static_cast<uint64_t>(destHeight) > std::numeric_limits<UINT>::max()) {
        return E_INVALIDARG;
    }

    D3D11_TEXTURE2D_DESC sourceDesc = {};
    sourceTexture->GetDesc(&sourceDesc);
    if (sourceDesc.Width == 0 || sourceDesc.Height == 0 ||
        sourceDesc.Format != DXGI_FORMAT_B8G8R8A8_UNORM) {
        return E_INVALIDARG;
    }

    const uint64_t sourceRight = static_cast<uint64_t>(sourceOffsetX) +
                                 static_cast<uint64_t>(destWidth);
    const uint64_t sourceBottom = static_cast<uint64_t>(sourceOffsetY) +
                                  static_cast<uint64_t>(destHeight);
    if (static_cast<uint64_t>(sourceOffsetX) >= sourceDesc.Width ||
        static_cast<uint64_t>(sourceOffsetY) >= sourceDesc.Height ||
        sourceRight > sourceDesc.Width ||
        sourceBottom > sourceDesc.Height) {
        return E_UNEXPECTED;
    }

    const size_t destRowBytes = static_cast<size_t>(destWidth) * 4u;
    if (destRowBytes / 4u != static_cast<size_t>(destWidth) ||
        static_cast<size_t>(destHeight) > std::numeric_limits<size_t>::max() / destRowBytes) {
        return E_INVALIDARG;
    }
    const size_t outputBytes = destRowBytes * static_cast<size_t>(destHeight);

    D3D11_TEXTURE2D_DESC stagingDesc = {};
    stagingDesc.Width = static_cast<UINT>(destWidth);
    stagingDesc.Height = static_cast<UINT>(destHeight);
    stagingDesc.MipLevels = 1;
    stagingDesc.ArraySize = 1;
    stagingDesc.SampleDesc.Count = 1;
    stagingDesc.SampleDesc.Quality = 0;
    stagingDesc.Usage = D3D11_USAGE_STAGING;
    stagingDesc.BindFlags = 0;
    stagingDesc.CPUAccessFlags = D3D11_CPU_ACCESS_READ;
    stagingDesc.MiscFlags = 0;
    stagingDesc.Format = DXGI_FORMAT_B8G8R8A8_UNORM;

    Microsoft::WRL::ComPtr<ID3D11Texture2D> stagingTexture;
    HRESULT hr = device->CreateTexture2D(&stagingDesc, nullptr, stagingTexture.GetAddressOf());
    if (FAILED(hr)) return hr;

    Microsoft::WRL::ComPtr<ID3D11DeviceContext> context;
    device->GetImmediateContext(context.GetAddressOf());
    if (!context) return E_FAIL;

    D3D11_BOX srcBox = {};
    srcBox.left = static_cast<UINT>(sourceOffsetX);
    srcBox.top = static_cast<UINT>(sourceOffsetY);
    srcBox.front = 0;
    srcBox.right = static_cast<UINT>(sourceRight);
    srcBox.bottom = static_cast<UINT>(sourceBottom);
    srcBox.back = 1;
    context->CopySubresourceRegion(stagingTexture.Get(), 0, 0, 0, 0,
                                   sourceTexture, 0, &srcBox);

    D3D11_MAPPED_SUBRESOURCE mapped = {};
    hr = context->Map(stagingTexture.Get(), 0, D3D11_MAP_READ, 0, &mapped);
    if (FAILED(hr) || !mapped.pData || mapped.RowPitch < destRowBytes) {
        if (SUCCEEDED(hr)) context->Unmap(stagingTexture.Get(), 0);
        return FAILED(hr) ? hr : E_UNEXPECTED;
    }

    outPixels.resize(outputBytes);
    for (int row = 0; row < destHeight; ++row) {
        const uint8_t* src = static_cast<const uint8_t*>(mapped.pData) +
                             static_cast<size_t>(row) * mapped.RowPitch;
        uint8_t* dst = outPixels.data() + static_cast<size_t>(row) * destRowBytes;
        std::memcpy(dst, src, destRowBytes);
    }

    context->Unmap(stagingTexture.Get(), 0);
    return S_OK;
}

void WriteTerminalOutcome(EventWriter& writer, const CaptureOutcome& outcome) {
    switch (outcome.result) {
        case CaptureResult::Failed:
            writer.Fail(outcome.errorCode, outcome.reason, outcome.hresult,
                        outcome.partialOutputPath, outcome.framesCaptured,
                        outcome.bytesWritten, outcome.encoderMode,
                        outcome.encoderSelectionReason, outcome.encoderSelectionKnown);
            break;
        case CaptureResult::Stopped:
            writer.Stopped(outcome.framesCaptured, outcome.framesDropped,
                           outcome.durationMs, outcome.bytesWritten,
                           outcome.width, outcome.height, outcome.encoderMode,
                           outcome.encoderSelectionReason, outcome.encoderSelectionKnown);
            break;
        case CaptureResult::Success:
            writer.Ok(outcome.framesCaptured, outcome.framesDropped,
                      outcome.durationMs, outcome.bytesWritten,
                      outcome.width, outcome.height, outcome.encoderMode,
                      outcome.encoderSelectionReason, outcome.encoderSelectionKnown);
            break;
        default:
            writer.Fail("internal_error",
                        "unexpected capture outcome result value",
                        "", outcome.partialOutputPath,
                        outcome.framesCaptured, outcome.bytesWritten);
            break;
    }
}

bool EncoderSelectionMatchesRequest(
    EncoderMode requestedMode,
    EncoderMode actualMode,
    EncoderSelectionReason reason,
    bool known) {
    if (!known) return false;
    if (requestedMode == EncoderMode::Software) {
        return actualMode == EncoderMode::Software &&
               reason == EncoderSelectionReason::SoftwareDefault;
    }
    if (actualMode == EncoderMode::Hardware) {
        return reason == EncoderSelectionReason::HardwareSelected;
    }
    if (actualMode != EncoderMode::Software) return false;
    return reason == EncoderSelectionReason::HardwareUnavailableFallback ||
           reason == EncoderSelectionReason::HardwareInitFailedFallback ||
           reason == EncoderSelectionReason::HardwareUnverifiedFallback;
}

CaptureOutcome NormalizeFailureEvidence(CaptureOutcome outcome,
                                        const std::wstring& canonicalPartialPath) {
    if (outcome.result != CaptureResult::Failed) {
        return outcome;
    }

    RemoveEmptyPartial(canonicalPartialPath);

    if (!canonicalPartialPath.empty() && FileExists(canonicalPartialPath)) {
        const int64_t size = GetFileSize(canonicalPartialPath);
        if (size > 0) {
            outcome.partialOutputPath = canonicalPartialPath;
            outcome.bytesWritten = size;
            return outcome;
        }
    }

    outcome.partialOutputPath.clear();
    outcome.bytesWritten = 0;
    return outcome;
}

CaptureSession::CaptureSession(const Options& options,
                               const std::wstring& outputPath,
                               const std::wstring& partialOutputPath,
                               BeginGate& gate,
                               EventWriter& writer)
    : options_(options),
      outputPath_(outputPath),
      partialOutputPath_(partialOutputPath),
      gate_(gate),
      writer_(writer),
      hooks_() {}

void CaptureSession::SetTestHooks(const CaptureSessionTestHooks& hooks) {
    hooks_ = hooks;
    // The test hook API is intentionally hermetic. A real WGC platform probe
    // remains a separate bounded integration check, while these tests exercise
    // the production coordinator, queue, encoder, teardown, and evidence
    // paths without requiring GraphicsCaptureItem activation.
    hooks_.useSyntheticPlatformResources = true;
}

CaptureOutcome CaptureSession::Run() {
    HRESULT hr = CoInitializeEx(nullptr, COINIT_MULTITHREADED);
    const bool comInitialized = SUCCEEDED(hr);
    if (FAILED(hr) && hr != RPC_E_CHANGED_MODE) {
        return MakeEarlyFail("com_init_failed", "CoInitializeEx failed", HresultToString(hr));
    }
    struct ComGuard {
        bool needUninit;
        ~ComGuard() { if (needUninit) CoUninitialize(); }
    } comGuard{comInitialized};

    Microsoft::WRL::ComPtr<ID3D11Device> d3dDevice;
    Microsoft::WRL::ComPtr<ID3D11DeviceContext> d3dContext;
    GraphicsCaptureItem item{nullptr};
    IDirect3DDevice device{nullptr};
    Direct3D11CaptureFramePool framePool{nullptr};
    GraphicsCaptureSession session{nullptr};
    bool hasCaptureResources = false;
    bool hasItemClosedSubscription = false;
    winrt::event_token itemClosedToken{};

    if (options_.mode != CaptureMode::ContinuousDisplay &&
        options_.mode != CaptureMode::ContinuousWindow &&
        options_.mode != CaptureMode::ContinuousRegion) {
        return MakeEarlyFail("invalid_target", "Unsupported continuous capture target");
    }

    int sourceWidth = 64;
    int sourceHeight = 64;
    int cropOffsetX = 0;
    int cropOffsetY = 0;
    MonitorEnumContext monitorCtx;
    if (!hooks_.useSyntheticPlatformResources) {
        if (options_.mode == CaptureMode::ContinuousDisplay ||
            options_.mode == CaptureMode::ContinuousRegion) {
            monitorCtx.target = options_.displayBounds;
            ::EnumDisplayMonitors(nullptr, nullptr, MonitorEnumProc, reinterpret_cast<LPARAM>(&monitorCtx));
            if (monitorCtx.match == nullptr) {
                return MakeEarlyFail("display_not_found", "No display exactly matches the requested bounds");
            }
            if (monitorCtx.matchCount > 1) {
                return MakeEarlyFail("display_ambiguous", "Multiple displays match the requested bounds");
            }
        } else {
            if (options_.windowHwnd > static_cast<std::uint64_t>(std::numeric_limits<ULONG_PTR>::max())) {
                return MakeEarlyFail("invalid_window_handle", "HWND exceeds the native pointer width");
            }
            HWND hwnd = reinterpret_cast<HWND>(static_cast<ULONG_PTR>(options_.windowHwnd));
            if (!::IsWindow(hwnd)) {
                return MakeEarlyFail("window_not_found", "The target window no longer exists");
            }
            if (::IsIconic(hwnd)) {
                return MakeEarlyFail("window_minimized", "The target window is minimized");
            }
            RECT windowRect = {};
            if (!::GetWindowRect(hwnd, &windowRect) ||
                windowRect.right <= windowRect.left || windowRect.bottom <= windowRect.top) {
                return MakeEarlyFail("window_unavailable", "The target window has no capturable bounds");
            }
        }

        hr = CreateD3D11Device(d3dDevice, d3dContext);
        if (FAILED(hr)) {
            hr = D3D11CreateDevice(nullptr, D3D_DRIVER_TYPE_WARP, nullptr,
                                   D3D11_CREATE_DEVICE_BGRA_SUPPORT,
                                   nullptr, 0, D3D11_SDK_VERSION,
                                   &d3dDevice, nullptr, &d3dContext);
            if (FAILED(hr)) {
                return MakeEarlyFail("d3d11_init_failed", "D3D11 device creation failed", HresultToString(hr));
            }
        }

        Microsoft::WRL::ComPtr<IDXGIDevice> dxgiDevice;
        hr = d3dDevice.As(&dxgiDevice);
        if (FAILED(hr)) {
            return MakeEarlyFail("dxgi_device_failed", "Failed to get DXGI device", HresultToString(hr));
        }

        hr = CreateDirect3D11DeviceFromDXGIDevice(dxgiDevice.Get(),
                                                  reinterpret_cast<IInspectable**>(winrt::put_abi(device)));
        if (FAILED(hr)) {
            return MakeEarlyFail("direct3d_device_failed", "CreateDirect3D11DeviceFromDXGIDevice failed", HresultToString(hr));
        }

        {
            auto factory = winrt::get_activation_factory<GraphicsCaptureItem, IGraphicsCaptureItemInterop>();
            if (!factory) {
                return MakeEarlyFail(options_.mode == CaptureMode::ContinuousWindow
                                         ? "window_factory_failed"
                                         : "wgc_factory_failed",
                                     "Failed to get GraphicsCaptureItem factory");
            }
            winrt::Windows::Graphics::Capture::GraphicsCaptureItem abiItem{nullptr};
            if (options_.mode == CaptureMode::ContinuousDisplay ||
                options_.mode == CaptureMode::ContinuousRegion) {
                hr = factory->CreateForMonitor(
                    monitorCtx.match,
                    winrt::guid_of<winrt::Windows::Graphics::Capture::GraphicsCaptureItem>(),
                    reinterpret_cast<void**>(winrt::put_abi(abiItem)));
            } else {
                HWND hwnd = reinterpret_cast<HWND>(static_cast<ULONG_PTR>(options_.windowHwnd));
                hr = factory->CreateForWindow(
                    hwnd,
                    winrt::guid_of<winrt::Windows::Graphics::Capture::GraphicsCaptureItem>(),
                    reinterpret_cast<void**>(winrt::put_abi(abiItem)));
            }
            if (FAILED(hr)) {
                return MakeEarlyFail(options_.mode == CaptureMode::ContinuousWindow
                                         ? "window_item_failed"
                                         : "wgc_item_failed",
                                     options_.mode == CaptureMode::ContinuousWindow
                                         ? "CreateForWindow failed"
                                         : "CreateForMonitor failed",
                                     HresultToString(hr));
            }
            item = abiItem;
        }

        const auto displaySize = item.Size();
        sourceWidth = displaySize.Width;
        sourceHeight = displaySize.Height;
        if (options_.mode == CaptureMode::ContinuousRegion &&
            (sourceWidth != options_.displayBounds.width ||
             sourceHeight != options_.displayBounds.height)) {
            return MakeEarlyFail("display_size_mismatch",
                                 "WGC display item size does not match display-bounds");
        }
    } else if (hooks_.onCreateCaptureItem) {
        CaptureSessionTestTargetRequest request;
        request.mode = options_.mode;
        request.displayBounds = options_.displayBounds;
        request.regionBounds = options_.regionBounds;
        request.windowHwnd = options_.windowHwnd;
        try {
            hr = hooks_.onCreateCaptureItem(request);
        } catch (...) {
            hr = E_FAIL;
        }
        if (FAILED(hr)) {
            return MakeEarlyFail(options_.mode == CaptureMode::ContinuousWindow
                                     ? "window_item_failed"
                                     : "wgc_item_failed",
                                 options_.mode == CaptureMode::ContinuousWindow
                                     ? "CreateForWindow test seam failed"
                                     : "CreateForMonitor test seam failed",
                                 HresultToString(hr));
        }
    }

    int captureWidth = 0;
    int captureHeight = 0;
    if (options_.mode == CaptureMode::ContinuousRegion) {
        if (!TryGetRegionCrop(options_.displayBounds, options_.regionBounds,
                              cropOffsetX, cropOffsetY)) {
            return MakeEarlyFail("invalid_region_bounds",
                                 "Region bounds are not an even, contained crop of display-bounds");
        }
        if (!ComputeCaptureDimensions(options_.regionBounds.width,
                                      options_.regionBounds.height,
                                      captureWidth, captureHeight)) {
            return MakeEarlyFail("region_size_unsupported",
                                 std::format("Region size {}x{} is too small for capture",
                                             options_.regionBounds.width,
                                             options_.regionBounds.height));
        }
    } else if (!ComputeCaptureDimensions(sourceWidth, sourceHeight, captureWidth, captureHeight)) {
        return MakeEarlyFail(options_.mode == CaptureMode::ContinuousWindow
                                 ? "window_size_unsupported"
                                 : "display_size_unsupported",
                             std::format("Capture target size {}x{} is too small for capture", sourceWidth, sourceHeight));
    }

    constexpr int kFramePoolBufferCount = 2;
    if (!hooks_.useSyntheticPlatformResources) {
        const auto pixelFormat = DirectXPixelFormat::B8G8R8A8UIntNormalized;
        framePool = Direct3D11CaptureFramePool::CreateFreeThreaded(
            device, pixelFormat, kFramePoolBufferCount, item.Size());
        session = framePool.CreateCaptureSession(item);
        hasCaptureResources = true;
    }

    // Leave the privacy border at its system-default value.

    auto state = std::make_shared<CapturePipelineState>(static_cast<size_t>(kFramePoolBufferCount - 1));
    state->sourceWidth = sourceWidth;
    state->sourceHeight = sourceHeight;

    if (hooks_.onStateCreated) {
        hooks_.onStateCreated(&state->lifecycle, state);
    }
    if (hooks_.onTestSignalsCreated) {
        CaptureSessionTestSignals signals;
        signals.signalWindowClosed = [state]() {
            state->SignalWindowClosed();
        };
        signals.signalWindowMinimized = [state]() {
            state->SignalWindowMinimized();
        };
        signals.signalDisplayUnavailable = [state]() {
            state->SignalDisplayUnavailable();
        };
        signals.signalSizeChanged = [state]() {
            state->SignalSizeChanged();
        };
        hooks_.onTestSignalsCreated(signals);
    }

    std::unique_ptr<WindowLifecycleMonitor> windowMonitor;
    if (options_.mode == CaptureMode::ContinuousWindow) {
        auto queryWindowState = [this](std::uint64_t hwndValue) {
            if (hooks_.useSyntheticPlatformResources) {
                if (hooks_.onWindowStateQuery) {
                    return hooks_.onWindowStateQuery(hwndValue);
                }
                return CaptureSessionTestWindowState{};
            }

            CaptureSessionTestWindowState state;
            if (hwndValue > static_cast<std::uint64_t>(std::numeric_limits<ULONG_PTR>::max())) {
                state.isWindow = false;
                return state;
            }
            HWND hwnd = reinterpret_cast<HWND>(static_cast<ULONG_PTR>(hwndValue));
            state.isWindow = ::IsWindow(hwnd) != FALSE;
            state.isIconic = state.isWindow && (::IsIconic(hwnd) != FALSE);
            return state;
        };
        windowMonitor = std::make_unique<WindowLifecycleMonitor>(
            options_.windowHwnd,
            std::move(queryWindowState),
            [state]() { state->SignalWindowClosed(); },
            [state]() { state->SignalWindowMinimized(); });
    }

    std::unique_ptr<DisplayLifecycleMonitor> displayMonitor;
    if (options_.mode == CaptureMode::ContinuousDisplay ||
        options_.mode == CaptureMode::ContinuousRegion) {
        const HMONITOR approvedMonitor = monitorCtx.match;
        auto queryDisplayAvailability = [this, approvedMonitor](const Rect& target) {
            if (hooks_.useSyntheticPlatformResources) {
                if (hooks_.onDisplayAvailabilityQuery) {
                    return hooks_.onDisplayAvailabilityQuery(target);
                }
                return true;
            }
            // Pair the approved bounds with the original HMONITOR handle so
            // a newly enumerated display at the same coordinates is not
            // treated as the original target. The WGC Closed event remains
            // the identity-loss signal; this poll is the bounded fallback for
            // topology loss when Closed is delayed or not delivered.
            return IsConfiguredDisplayAvailable(target, approvedMonitor);
        };
        displayMonitor = std::make_unique<DisplayLifecycleMonitor>(
            options_.displayBounds,
            std::move(queryDisplayAvailability),
            [state]() { state->SignalDisplayUnavailable(); });
    }

    if (hasCaptureResources) {
        itemClosedToken = item.Closed([state, mode = options_.mode](GraphicsCaptureItem const&, winrt::Windows::Foundation::IInspectable const&) {
            if (mode == CaptureMode::ContinuousWindow) {
                state->SignalWindowClosed();
            } else {
                state->SignalDisplayUnavailable();
            }
        });
        hasItemClosedSubscription = true;
    }

    FrameTimeline timeline(options_.fps);
    VideoEncoder encoder;
    std::string encoderError;
    std::string encoderHresult;

    auto writeFrame = [&](const std::vector<uint8_t>& pixels,
                          int64_t mediaTimeHns,
                          int64_t durationHns) -> EncoderResult {
        EncoderResult result;
        if (hooks_.onWriteFrame) {
            result = hooks_.onWriteFrame(pixels, mediaTimeHns, durationHns);
        } else {
            result = encoder.WriteFrame(pixels, mediaTimeHns, durationHns);
        }
        if (result.status == EncoderStatus::Ok) {
            state->framesCaptured.fetch_add(1);
        }
        return result;
    };

    auto finalizeEncoder = [&]() -> EncoderResult {
        if (hooks_.onFinalize) {
            return hooks_.onFinalize();
        }
        return encoder.Finalize();
    };

    // Media Foundation sample duration belongs to the sample that starts at
    // the timestamp. The next accepted frame is the first trustworthy end of
    // the current frame, so retain one copied frame and close it on the next
    // timestamp or at the authorized capture end.
    struct PendingFrame {
        std::vector<uint8_t> pixels;
        int64_t mediaTimeHns = 0;
    };
    std::optional<PendingFrame> pendingFrame;
    int64_t captureEndMediaHns = 0;

    auto writePendingAt = [&](int64_t endMediaHns) -> bool {
        if (!pendingFrame) {
            return true;
        }
        if (endMediaHns <= pendingFrame->mediaTimeHns) {
            pendingFrame.reset();
            return true;
        }

        EncoderResult result = writeFrame(
            pendingFrame->pixels,
            pendingFrame->mediaTimeHns,
            endMediaHns - pendingFrame->mediaTimeHns);
        pendingFrame.reset();
        if (result.status == EncoderStatus::Ok) {
            return true;
        }

        encoderError = result.error;
        encoderHresult = result.hresult;
        state->SignalCaptureFailure();
        return false;
    };

    auto writePendingUntil = [&](int64_t endMediaHns) -> bool {
        if (!pendingFrame) {
            return true;
        }

        int64_t mediaTimeHns = 0;
        int64_t durationHns = 0;
        if (!timeline.FinalizeAt(endMediaHns, &mediaTimeHns, &durationHns) ||
            mediaTimeHns != pendingFrame->mediaTimeHns) {
            // The final accepted frame was at or after the capture end and is
            // not a playable interval. Do not extend the media past the end.
            pendingFrame.reset();
            return true;
        }

        return writePendingAt(mediaTimeHns + durationHns);
    };

    winrt::event_token frameToken{};
    if (hasCaptureResources) {
        frameToken = framePool.FrameArrived(
        [state](Direct3D11CaptureFramePool const& sender, winrt::Windows::Foundation::IInspectable const&) {
            CallbackGuard guard(state->lifecycle);
            if (!guard.Entered()) {
                return;
            }

            try {
                if (state->stopRequested.load() ||
                    state->coordinator.State() != StartupState::CaptureActive) {
                    return;
                }

                auto frame = sender.TryGetNextFrame();
                if (!frame) return;

                const auto contentSize = frame.ContentSize();
                if (IsContentSizeChanged(state->sourceWidth, state->sourceHeight,
                                         contentSize.Width, contentSize.Height)) {
                    state->SignalSizeChanged();
                    return;
                }

                QueuedFrame qf;
                qf.frame = frame;
                qf.systemRelativeTimeHns = frame.SystemRelativeTime().count();
                qf.contentWidth = contentSize.Width;
                qf.contentHeight = contentSize.Height;

                if (!state->queue.Push(qf)) {
                    // Queue rejected the frame (shutdown). Close it here.
                    if (qf.frame) {
                        try {
                            qf.frame.Close();
                        } catch (...) {
                        }
                    }
                }
            } catch (...) {
                state->framesDropped.fetch_add(1);
            }
        });
    }

    ScopedThread encoderThread{std::thread([&, state]() {
        // Wait for begin authorization before initializing anything that would
        // write screen frames. This guarantees that a COM/encoder failure is
        // reported while the coordinator is in EncoderInitializing.
        if (!state->coordinator.WaitForBeginAuthorization(std::chrono::milliseconds(options_.beginTimeoutMs + 1000))) {
            return;
        }

        HRESULT comHr = CoInitializeEx(nullptr, COINIT_MULTITHREADED);
        const bool threadComInitialized = SUCCEEDED(comHr);
        if (FAILED(comHr) && comHr != RPC_E_CHANGED_MODE) {
            state->coordinator.SignalEncoderFailed("COM initialization failed for encoder thread",
                                                   HresultToString(comHr));
            return;
        }
        struct ThreadComGuard {
            bool need;
            ~ThreadComGuard() { if (need) CoUninitialize(); }
        } threadComGuard{threadComInitialized};

        EncoderResult initResult;
        if (hooks_.onEncoderInitialize && options_.encoderMode != EncoderMode::Software) {
            initResult.status = EncoderStatus::InitializeFailed;
            initResult.error = "encoder_selection_policy_mismatch: hardware-preferred requires the mode-aware encoder hook";
            initResult.hresult = "0x80004005";
        } else if (hooks_.onEncoderInitialize) {
            initResult = hooks_.onEncoderInitialize(captureWidth, captureHeight, options_.fps,
                                                     partialOutputPath_);
        } else if (hooks_.onEncoderInitializeWithMode) {
            initResult = hooks_.onEncoderInitializeWithMode(captureWidth, captureHeight, options_.fps,
                                                            partialOutputPath_, options_.encoderMode);
        } else {
            initResult = encoder.Initialize(captureWidth, captureHeight, options_.fps, partialOutputPath_,
                                            options_.encoderMode);
        }
        if (initResult.status != EncoderStatus::Ok) {
            state->coordinator.SignalEncoderFailed(initResult.error, initResult.hresult);
            return;
        }

        // The legacy test hook predates encoder selection evidence. It is only
        // a valid seam for an explicitly requested software session; a
        // hardware-preferred request must use the mode-aware hook or the real
        // VideoEncoder, otherwise it would silently fake software_default.
        if (!initResult.selectionKnown) {
            if (options_.encoderMode == EncoderMode::Software) {
                initResult.encoderMode = EncoderMode::Software;
                initResult.selectionReason = EncoderSelectionReason::SoftwareDefault;
                initResult.selectionKnown = true;
            } else {
                state->coordinator.SignalEncoderFailed(
                    "encoder_selection_policy_mismatch",
                    "hardware-preferred encoder initialization did not provide selection evidence");
                return;
            }
        }

        if (!EncoderSelectionMatchesRequest(
                options_.encoderMode,
                initResult.encoderMode,
                initResult.selectionReason,
                initResult.selectionKnown)) {
            state->coordinator.SignalEncoderFailed(
                "encoder_selection_policy_mismatch",
                "encoder selection does not match the requested mode");
            return;
        }

        state->encoderMode = initResult.encoderMode;
        state->encoderSelectionReason = initResult.selectionReason;
        state->encoderSelectionKnown = initResult.selectionKnown;

        state->coordinator.SignalEncoderReady();

        if (!state->coordinator.WaitForCaptureActive(std::chrono::milliseconds(options_.beginTimeoutMs + 1000))) {
            return;
        }

        const int64_t beginTimeMs = state->coordinator.BeginTimeMs();
        const int64_t endTimeMs = beginTimeMs + options_.durationMs;

        // Explicit first-frame evidence is published exactly once by this
        // worker thread, promptly after the first source frame has been
        // accepted by the timeline and copied/staged successfully. It never
        // waits for encoder finalization and never falsifies framesCaptured.
        bool firstFramePublished = false;

        while (!state->captureEnded.load()) {
            QueuedFrame qf;
            bool gotFrame = state->queue.Pop(qf, std::chrono::milliseconds(50));

            const auto nowMs = SteadyMs(std::chrono::steady_clock::now());
            captureEndMediaHns = std::max<int64_t>(
                0, (nowMs - beginTimeMs) * 10'000LL);
            if (nowMs >= endTimeMs || state->stopRequested.load() ||
                state->coordinator.State() == StartupState::Stopping ||
                state->coordinator.State() == StartupState::Stopped) {
                if (qf.frame) {
                    try { qf.frame.Close(); } catch (...) {}
                }
                break;
            }

            if (gotFrame && (qf.frame || hooks_.onCopyFrame)) {
                int64_t mediaTimeHns = 0;
                int64_t durationHns = 0;
                if (!timeline.SubmitFrame(
                        qf.systemRelativeTimeHns,
                        &mediaTimeHns,
                        &durationHns,
                        !hooks_.useSyntheticPlatformResources && captureEndMediaHns > 0
                            ? captureEndMediaHns
                            : -1)) {
                    state->framesDropped.fetch_add(1);
                    if (qf.frame) {
                        try { qf.frame.Close(); } catch (...) {}
                    }
                    continue;
                }

                std::vector<uint8_t> pixels;
                HRESULT copyHr = S_OK;
                if (hooks_.onCopyFrame) {
                    if (!hooks_.onCopyFrame(qf, captureWidth, captureHeight, pixels)) {
                        copyHr = E_FAIL;
                    }
                } else {
                    copyHr = CopyFrameToBgra(d3dDevice.Get(), qf.frame,
                                             captureWidth, captureHeight,
                                             cropOffsetX, cropOffsetY, pixels);
                }
                if (qf.frame) {
                    try { qf.frame.Close(); } catch (...) {}
                }

                if (FAILED(copyHr)) {
                    // The accepted timestamp still supplies a trustworthy
                    // boundary for the previous copied sample. Preserve that
                    // sample before reporting the GPU copy failure.
                    writePendingAt(mediaTimeHns);
                    state->copyFailedHr.store(copyHr);
                    state->SignalCaptureFailure();
                    break;
                }

                if (!firstFramePublished) {
                    // At this point the session has passed authenticated begin,
                    // StartCapture has succeeded, a source frame has arrived,
                    // the timeline has accepted it, and the GPU-to-BGRA copy has
                    // succeeded. This is the only place FIRST_FRAME may fire.
                    firstFramePublished = true;
                    const int64_t firstFrameElapsedMs = std::max<int64_t>(
                        0, SteadyMs(std::chrono::steady_clock::now()) - beginTimeMs);
                    writer_.FirstFrame(1, firstFrameElapsedMs);
                    if (hooks_.onFirstFrame) {
                        hooks_.onFirstFrame(1, firstFrameElapsedMs);
                    }
                }

                if (pendingFrame) {
                    if (!writePendingAt(mediaTimeHns)) {
                        state->SignalCaptureFailure();
                        break;
                    }
                }

                pendingFrame = PendingFrame{std::move(pixels), mediaTimeHns};
                if (state->captureFailed.load()) {
                    break;
                }
            }
        }

        if (captureEndMediaHns <= 0) {
            captureEndMediaHns = static_cast<int64_t>(options_.durationMs) * 10'000LL;
        }
        if (!state->captureFailed.load()) {
            writePendingUntil(captureEndMediaHns);
        }

        state->queue.Shutdown();
        EncoderResult finalizeResult = finalizeEncoder();
        if (finalizeResult.status != EncoderStatus::Ok && encoderError.empty()) {
            encoderError = finalizeResult.error;
            encoderHresult = finalizeResult.hresult;
            state->SignalCaptureFailure();
        }
    })};

    // Single begin time used for both coordinator and duration measurement.
    std::chrono::steady_clock::time_point beginTime;

    // Production source for "bytes written" evidence: the partial file's real
    // size on disk. Tests can override this to avoid depending on a real
    // encoder, but the override must still represent file-size semantics.
    auto GetOutputBytes = [&]() -> int64_t {
        if (hooks_.onGetOutputBytes) {
            return hooks_.onGetOutputBytes();
        }
        if (partialOutputPath_.empty()) {
            return 0;
        }
        return GetFileSize(partialOutputPath_);
    };

    // RAII guard that guarantees coordinator.MarkCaptureEnded() is invoked
    // exactly once on every return path after state has been created. This is
    // distinct from the IPC terminal event, which is owned by main.cpp.
    struct CaptureEndedGuard {
        StartupCoordinator& coordinator;
        std::function<void()> onMarkCaptureEnded;
        ~CaptureEndedGuard() {
            if (onMarkCaptureEnded) onMarkCaptureEnded();
            coordinator.MarkCaptureEnded();
        }
    };
    CaptureEndedGuard captureEndedGuard{state->coordinator, hooks_.onMarkCaptureEnded};

    auto FailAndTeardown = [&](const std::string& errorCode,
                               const std::string& reason,
                               const std::string& hresult = "") -> CaptureOutcome {
        const auto stopDecisionTime = std::chrono::steady_clock::now();
        const int64_t durationMs = (beginTime.time_since_epoch().count() > 0)
            ? std::chrono::duration_cast<std::chrono::milliseconds>(stopDecisionTime - beginTime).count()
            : 0;
        const int64_t framesCaptured = state->framesCaptured.load();
        const int64_t framesDropped = state->framesDropped.load() + state->queue.Dropped();

        state->RequestStop(false);
        state->captureEnded.store(true);
        state->queue.Shutdown();
        encoderThread.Join();

        bool callbackDrainTimeout = false;
        TeardownFramePool(hasCaptureResources, item, hasItemClosedSubscription, itemClosedToken,
                          frameToken, session, framePool, state, &callbackDrainTimeout);

        auto [partialPath, bytesWritten] = GetPartialEvidence(partialOutputPath_);
        if (callbackDrainTimeout) {
            CaptureOutcome outcome = MakeFailWithEvidence("callback_drain_timeout",
                                                          "Timed out waiting for frame callbacks to exit",
                                                          "", partialPath,
                                                          framesCaptured, framesDropped, durationMs, bytesWritten,
                                                          captureWidth, captureHeight);
            outcome.encoderMode = state->encoderMode;
            outcome.encoderSelectionReason = state->encoderSelectionReason;
            outcome.encoderSelectionKnown = state->encoderSelectionKnown;
            return outcome;
        }
        CaptureOutcome outcome = MakeFailWithEvidence(errorCode, reason, hresult, partialPath,
                                                      framesCaptured, framesDropped, durationMs, bytesWritten,
                                                      captureWidth, captureHeight);
        outcome.encoderMode = state->encoderMode;
        outcome.encoderSelectionReason = state->encoderSelectionReason;
        outcome.encoderSelectionKnown = state->encoderSelectionKnown;
        return outcome;
    };

    // Wait for begin authorization before touching capture session.
    BeginGateResult gateResult = gate_.WaitAndRun([&]() {
        state->coordinator.AuthorizeBegin();
    });

    if (gateResult != BeginGateResult::Started) {
        // Ensure the encoder worker exits cleanly.
        state->coordinator.AuthorizeBegin();
        state->coordinator.SignalEncoderFailed("begin_not_granted", "");
        state->captureEnded.store(true);
        state->queue.Shutdown();
        encoderThread.Join();

        bool callbackDrainTimeout = false;
        TeardownFramePool(hasCaptureResources, item, hasItemClosedSubscription, itemClosedToken,
                          frameToken, session, framePool, state, &callbackDrainTimeout);

        // Begin failures only produce an empty placeholder; do not report it.
        RemoveEmptyPartial(partialOutputPath_);

        switch (gateResult) {
            case BeginGateResult::Timeout:
                return MakeEarlyFail("timeout", "Begin signal not received before timeout");
            case BeginGateResult::Cancelled:
                return MakeEarlyFail("cancelled", "Capture was cancelled before begin");
            case BeginGateResult::InvalidToken:
                return MakeEarlyFail("invalid_token", "Begin signal token mismatch");
            case BeginGateResult::CancelledBeforeBegin:
                return MakeEarlyFail("cancelled_before_begin", "Stop signal existed before begin authorization");
            case BeginGateResult::InternalError:
                return MakeEarlyFail("start_callback_failed", "StartCapture callback raised an exception");
            default:
                return MakeEarlyFail("begin_failed", "Failed to obtain begin authorization");
        }
    }

    // Wait for the encoder to finish initializing before starting capture.
    EncoderInitResult initResult = state->coordinator.WaitForEncoderInit(
        std::chrono::milliseconds(options_.beginTimeoutMs + 1000));

    if (initResult.status == EncoderInitStatus::TimedOut) {
        // A hung Media Foundation initialization cannot be cancelled from inside
        // the helper. Join the worker deterministically; if it never returns,
        // the parent process watchdog is responsible for terminating the helper.
        state->RequestStop(false);
        state->captureEnded.store(true);
        state->queue.Shutdown();
        encoderThread.Join();

        bool callbackDrainTimeout = false;
        TeardownFramePool(hasCaptureResources, item, hasItemClosedSubscription, itemClosedToken,
                          frameToken, session, framePool, state, &callbackDrainTimeout);

        auto [partialPath, bytesWritten] = GetPartialEvidence(partialOutputPath_);
        return MakeFailWithEvidence("encoder_init_timeout",
                                    "Encoder did not become ready in time",
                                    "", partialPath, 0, 0, 0, bytesWritten,
                                    captureWidth, captureHeight);
    }
    if (initResult.status == EncoderInitStatus::Failed) {
        return FailAndTeardown("encoder_init_failed", initResult.error, initResult.hresult);
    }
    if (initResult.status == EncoderInitStatus::Stopped) {
        return FailAndTeardown("stopped_before_capture", "Capture was stopped before capture became active");
    }

    // Revalidate the HWND immediately before StartCapture. A target can be
    // minimized or destroyed while consent and encoder initialization are in
    // flight; fail with target-specific evidence instead of starting a stale
    // item and waiting for a generic watchdog.
    if (!hooks_.useSyntheticPlatformResources &&
        options_.mode == CaptureMode::ContinuousWindow) {
        if (state->targetClosed.load()) {
            return FailAndTeardown("window_closed", "The target window closed before capture started");
        }
        if (options_.windowHwnd > static_cast<std::uint64_t>(std::numeric_limits<ULONG_PTR>::max())) {
            return FailAndTeardown("invalid_window_handle", "HWND exceeds the native pointer width");
        }
        HWND hwnd = reinterpret_cast<HWND>(static_cast<ULONG_PTR>(options_.windowHwnd));
        if (!::IsWindow(hwnd)) {
            return FailAndTeardown("window_not_found", "The target window no longer exists");
        }
        if (::IsIconic(hwnd)) {
            return FailAndTeardown("window_minimized", "The target window is minimized");
        }
        RECT windowRect = {};
        if (!::GetWindowRect(hwnd, &windowRect) ||
            windowRect.right <= windowRect.left || windowRect.bottom <= windowRect.top) {
            return FailAndTeardown("window_unavailable", "The target window has no capturable bounds");
        }
    }

    // Revalidate the approved display immediately before StartCapture. Consent
    // and encoder initialization may outlive the topology snapshot used to
    // create the WGC item.
    if (!hooks_.useSyntheticPlatformResources &&
        (options_.mode == CaptureMode::ContinuousDisplay ||
         options_.mode == CaptureMode::ContinuousRegion) &&
        !IsConfiguredDisplayAvailable(options_.displayBounds, monitorCtx.match)) {
        return FailAndTeardown("display_unavailable",
                               "The approved target display is no longer available");
    }

    // Single clock: record begin time, start capture, then publish active state.
    beginTime = std::chrono::steady_clock::now();
    const int64_t beginTimeMs = SteadyMs(beginTime);

    try {
        if (hooks_.onStartCapture) {
            hooks_.onStartCapture();
        } else {
            session.StartCapture();
        }
    } catch (...) {
        return FailAndTeardown("start_capture_failed", "StartCapture raised an exception");
    }

    const auto deadline = beginTime + std::chrono::milliseconds(options_.durationMs);

    const char* captureMethod = options_.mode == CaptureMode::ContinuousWindow
        ? "WGC_D3D11_WINDOW_FRAME_STREAM"
        : options_.mode == CaptureMode::ContinuousRegion
            ? "WGC_D3D11_REGION_FRAME_STREAM"
            : "WGC_D3D11_FRAME_STREAM";
    writer_.Started(WideToUtf8(options_.recordingId), outputPath_, options_.fps,
                    captureWidth, captureHeight, captureMethod,
                    state->encoderMode, state->encoderSelectionReason,
                    state->encoderSelectionKnown);
    if (hooks_.onStarted) {
        hooks_.onStarted();
    }
    state->coordinator.SignalCaptureStarted(beginTimeMs);

    // Target lifecycle monitors start only after authenticated begin, encoder
    // readiness, and StartCapture have all succeeded.
    if (windowMonitor) {
        windowMonitor->Start();
    }
    if (displayMonitor) {
        displayMonitor->Start();
    }

    if (hooks_.onCaptureActive) {
        hooks_.onCaptureActive(state->queue);
    }

    StopSignalWatcher stopWatcher(options_.stopSignalPath, state->stopRequested, state->userStopped,
                                  [&]() { state->loopCv.notify_all(); });
    stopWatcher.Start();

    ProgressScheduler scheduler([&](const ProgressSnapshot& snapshot) {
        writer_.Progress(snapshot.framesCaptured,
                         snapshot.framesDropped,
                         snapshot.elapsedMs,
                         snapshot.bytesWritten);
    }, std::chrono::milliseconds(1000));
    scheduler.Start(beginTimeMs);

    {
        std::unique_lock<std::mutex> lock(state->loopMutex);
        while (std::chrono::steady_clock::now() < deadline && !state->stopRequested.load()) {
            const auto now = std::chrono::steady_clock::now();
            ProgressSnapshot snapshot;
            snapshot.framesCaptured = state->framesCaptured.load();
            snapshot.framesDropped = state->framesDropped.load() + state->queue.Dropped();
            snapshot.elapsedMs = SteadyMs(now) - beginTimeMs;
            snapshot.bytesWritten = GetOutputBytes();
            if (hooks_.onProgressSnapshot) {
                hooks_.onProgressSnapshot(snapshot);
            }
            scheduler.MaybeEmit(snapshot);

            const auto waitUntil = std::min(deadline, scheduler.NextProgressTime());
            state->loopCv.wait_until(lock, waitUntil, [&] {
                return state->stopRequested.load() || state->captureFailed.load() ||
                       state->sizeChanged.load() || state->targetClosed.load() ||
                       state->targetMinimized.load() || state->displayUnavailable.load() ||
                       std::chrono::steady_clock::now() >= waitUntil;
            });
        }
    }

    const auto stopDecisionTime = std::chrono::steady_clock::now();
    const int64_t durationMs = std::chrono::duration_cast<std::chrono::milliseconds>(stopDecisionTime - beginTime).count();

    if (windowMonitor) {
        windowMonitor->Stop();
    }
    if (displayMonitor) {
        displayMonitor->Stop();
    }
    stopWatcher.Stop();
    scheduler.Stop();
    state->RequestStop(false);
    state->lifecycle.StopAccepting();

    // Teardown: stop producing frames, wait for callbacks, then stop consuming.
    bool callbackDrainTimeout = false;
    TeardownFramePool(hasCaptureResources, item, hasItemClosedSubscription, itemClosedToken,
                      frameToken, session, framePool, state, &callbackDrainTimeout);

    state->captureEnded.store(true);
    state->queue.Shutdown();
    encoderThread.Join();

    ProgressSnapshot finalSnapshot;
    finalSnapshot.framesCaptured = state->framesCaptured.load();
    finalSnapshot.framesDropped = state->framesDropped.load() + state->queue.Dropped();
    finalSnapshot.elapsedMs = durationMs;
    finalSnapshot.bytesWritten = GetOutputBytes();
    writer_.Progress(finalSnapshot.framesCaptured,
                     finalSnapshot.framesDropped,
                     finalSnapshot.elapsedMs,
                     finalSnapshot.bytesWritten);
    if (hooks_.onProgressSnapshot) {
        hooks_.onProgressSnapshot(finalSnapshot);
    }

    const int64_t framesCaptured = state->framesCaptured.load();
    const int64_t framesDropped = state->framesDropped.load() + state->queue.Dropped();

    CaptureOutcome outcome;

    if (callbackDrainTimeout) {
        auto [partialPath, bytesWritten] = GetPartialEvidence(partialOutputPath_);
        outcome = MakeFailWithEvidence("callback_drain_timeout",
                                       "Timed out waiting for frame callbacks to exit",
                                       "", partialPath,
                                       framesCaptured, framesDropped, durationMs, bytesWritten,
                                       captureWidth, captureHeight);
    } else if (state->runtimeSignal.load() == CapturePipelineState::RuntimeSignal::DisplayUnavailable ||
               state->displayUnavailable.load()) {
        auto [partialPath, bytesWritten] = GetPartialEvidence(partialOutputPath_);
        outcome = MakeFailWithEvidence("display_unavailable",
                                       "The approved target display is no longer available", "",
                                       partialPath, framesCaptured, framesDropped, durationMs,
                                       bytesWritten, captureWidth, captureHeight);
    } else if (state->runtimeSignal.load() == CapturePipelineState::RuntimeSignal::WindowClosed ||
               state->targetClosed.load()) {
        auto [partialPath, bytesWritten] = GetPartialEvidence(partialOutputPath_);
        outcome = MakeFailWithEvidence("window_closed", "The target window closed during capture", "",
                                       partialPath, framesCaptured, framesDropped, durationMs,
                                       bytesWritten, captureWidth, captureHeight);
    } else if (state->runtimeSignal.load() == CapturePipelineState::RuntimeSignal::WindowMinimized ||
               state->targetMinimized.load()) {
        auto [partialPath, bytesWritten] = GetPartialEvidence(partialOutputPath_);
        outcome = MakeFailWithEvidence("window_minimized", "The target window was minimized during capture", "",
                                       partialPath, framesCaptured, framesDropped, durationMs,
                                       bytesWritten, captureWidth, captureHeight);
    } else if (state->runtimeSignal.load() == CapturePipelineState::RuntimeSignal::SizeChanged ||
               state->sizeChanged.load()) {
        auto [partialPath, bytesWritten] = GetPartialEvidence(partialOutputPath_);
        outcome = MakeFailWithEvidence("size_changed", "Frame content size changed during capture", "",
                                       partialPath, framesCaptured, framesDropped, durationMs,
                                       bytesWritten, captureWidth, captureHeight);
    } else if (state->captureFailed.load()) {
        auto [partialPath, bytesWritten] = GetPartialEvidence(partialOutputPath_);
        if (state->copyFailedHr.load() != S_OK) {
            outcome = MakeFailWithEvidence("d3d_copy_failed", "Failed to copy frame from GPU",
                                           HresultToString(state->copyFailedHr.load()), partialPath,
                                           framesCaptured, framesDropped, durationMs, bytesWritten,
                                           captureWidth, captureHeight);
        } else if (!encoderError.empty()) {
            outcome = MakeFailWithEvidence("encoding_error", encoderError, encoderHresult, partialPath,
                                           framesCaptured, framesDropped, durationMs, bytesWritten,
                                           captureWidth, captureHeight);
        } else {
            outcome = MakeFailWithEvidence("capture_failed", "Capture failed during encoding", "", partialPath,
                                           framesCaptured, framesDropped, durationMs, bytesWritten,
                                           captureWidth, captureHeight);
        }
    } else if (framesCaptured == 0) {
        // No frames means the partial (if any) is not useful evidence.
        if (!partialOutputPath_.empty() && FileExists(partialOutputPath_)) {
            ::DeleteFileW(partialOutputPath_.c_str());
        }
        outcome = MakeFailWithEvidence("zero_frames", "No frames were captured", "", {},
                                       0, framesDropped, durationMs, 0,
                                       captureWidth, captureHeight);
    } else {
        // Common publish path for both Success and explicit user Stopped.
        if (!PublishPartialToFinal(partialOutputPath_, outputPath_)) {
            auto [partialPath, bytesWritten] = GetPartialEvidence(partialOutputPath_);
            const DWORD err = ::GetLastError();
            outcome = MakeFailWithEvidence("publish_failed",
                                           std::format("MoveFileEx failed: {}", err), "",
                                           partialPath, framesCaptured, framesDropped, durationMs,
                                           bytesWritten, captureWidth, captureHeight);
        } else {
            const int64_t finalSize = GetFileSize(outputPath_);
            if (finalSize == 0) {
                // Do not leave an invalid empty file at the target path.
                ::DeleteFileW(outputPath_.c_str());
                outcome = MakeFailWithEvidence("invalid_output",
                                               "Final output file is empty after publish", "", {},
                                               framesCaptured, framesDropped, durationMs, 0,
                                               captureWidth, captureHeight);
            } else {
                if (state->userStopped.load()) {
                    outcome.result = CaptureResult::Stopped;
                } else {
                    outcome.result = CaptureResult::Success;
                }
                outcome.framesCaptured = framesCaptured;
                outcome.framesDropped = framesDropped;
                outcome.durationMs = durationMs;
                outcome.bytesWritten = finalSize;
                outcome.width = captureWidth;
                outcome.height = captureHeight;
            }
        }
    }

    // CaptureSession returns a complete outcome; the terminal IPC event is
    // emitted exactly once by main.cpp (the single terminal owner).
    outcome.encoderMode = state->encoderMode;
    outcome.encoderSelectionReason = state->encoderSelectionReason;
    outcome.encoderSelectionKnown = state->encoderSelectionKnown;
    return outcome;
}

} // namespace wgc
